const app = document.getElementById("app");
const USER = localStorage.getItem("skillbridge_user") || "demo-student";
let role = localStorage.getItem("skillbridge_role") || "student";
let page = "dashboard";
let cache = { profile:null, opportunities:[], matches:[], applications:[], follows:[], pulse:null, career:null, market:null };

const esc = (v) => String(v ?? "").replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const pills = xs => (xs||[]).map(x=>`<span class="pill">${esc(x)}</span>`).join("");
const money = v => esc(v || "Not specified");

async function api(url, options={}) {
  const headers = new Headers(options.headers || {});
  headers.set("X-Local-User", USER);
  headers.set("X-Local-Role", role);
  if(options.body && !headers.has("Content-Type")) headers.set("Content-Type","application/json");
  const r = await fetch(url,{...options,headers});
  const data = await r.json().catch(()=>({}));
  if(!r.ok) throw new Error(data.error || `Request failed (${r.status})`);
  return data;
}
function shell(content) {
  const nav = role==='student' ? [['dashboard','Dashboard'],['discover','Discover Jobs'],['applications','Applications'],['pulse','SkillPulse'],['career','Career Path'],['interview','Interview Prep']] : [['dashboard','Overview'],['talent','Talent Market'],['post','Post Opportunity'],['intel','Market Intel']];
  app.innerHTML = `<div class="app-shell"><header class="topbar"><div class="brand"><div class="brand-mark">S</div><div><b>SkillBridge</b><small>Student Skill Matcher</small></div></div><nav>${nav.map(([k,l])=>`<button class="nav-btn ${page===k?'active':''}" data-page="${k}">${l}</button>`).join("")}</nav><div class="top-actions"><span class="role-badge">${role==='student'?'Student':'Organization'}</span><button id="switch-role" class="ghost">Switch role</button></div></header><main>${content}</main><footer>SkillBridge • local development mode</footer></div>`;
  document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render();});
  document.getElementById('switch-role').onclick=()=>{role=role==='student'?'organization':'student';localStorage.setItem('skillbridge_role',role);page='dashboard';render();};
}
const card=(title,body)=>`<section class="card"><div class="card-head"><h3>${title}</h3></div>${body}</section>`;
const hero=(title,sub)=>`<div class="hero"><div><span class="eyebrow">AI-POWERED CAREER PLATFORM</span><h1>${title}</h1><p>${sub}</p></div></div>`;
const stat=(label,value,sub)=>`<div class="stat"><span>${label}</span><b>${value}</b><small>${sub||''}</small></div>`;
async function loadStudent(){cache.profile=(await api('/api/students'))[0];if(!cache.profile)throw new Error('No student profile');const [o,m,a,f]=await Promise.all([api('/api/opportunities'),api(`/api/matches/${cache.profile.id}`),api('/api/applications'),api('/api/follows')]);cache.opportunities=o;cache.matches=m.matches||[];cache.applications=a;cache.follows=f;}
async function loadOrg(){cache.opportunities=await api('/api/opportunities');cache.market=await api('/api/market');}
function matchCard(m){const o=m.opportunity||m;return `<div class="match"><div><b>${esc(o.company)}</b><h4>${esc(o.title)}</h4><div>${pills(o.skills)}</div><small>${esc(o.location)} • ${esc(o.mode)} • ${money(o.stipend)}</small></div><div class="score">${Math.round(m.score||0)}<small>% fit</small></div></div>`;}
function dashboard(){const p=cache.profile||{};return hero(`Build your next move, ${esc(p.name||'student')}.`,'Discover roles that match your skills, understand your gaps, and turn your profile into a career plan.')+`<div class="stats">${stat('Profile skills',(p.skills||[]).length,'Keep adding evidence')}${stat('Job matches',cache.matches.length,'Ranked by fit')}${stat('Applications',cache.applications.length,'Track your pipeline')}${stat('Followed companies',cache.follows.length,'Stay in the loop')}</div><div class="grid-2">${card('AI Profile Builder',`<p>Describe yourself naturally and let SkillBridge extract useful profile signals.</p><textarea id="profile-text" placeholder="I am a second-year CSE student who knows Python, React and SQL. I built a hackathon project and want frontend or AI internships..."></textarea><button id="analyze-profile" class="primary">Analyze profile</button><div id="ai-out"></div>`)}${card('Recommended now',cache.matches.slice(0,4).map(matchCard).join('')||'<div class="empty">Add skills to unlock recommendations.</div>')}</div>`;}
function discover(){return hero('Discover opportunities','Search internships and jobs by company, role, skill, location and work mode.')+`<div class="filters"><input id="q" placeholder="Search role, company, skill…"><select id="mode"><option value="">Any mode</option><option>Remote</option><option>Hybrid</option><option>On-site</option><option>Flexible</option></select><button id="search" class="primary">Search</button></div><div class="job-grid">${cache.opportunities.map(jobCard).join('')}</div>`;}
function jobCard(o){const saved=cache.follows.some(f=>f.company===o.company),applied=cache.applications.some(a=>a.opportunityId===o.id);return `<article class="job-card"><div class="job-top"><span class="company">${esc(o.company)}</span><button class="icon-btn follow" data-company="${esc(o.company)}">${saved?'★':'☆'}</button></div><h3>${esc(o.title)}</h3><p>${esc(o.description)}</p><div>${pills(o.skills)}</div><div class="job-meta"><span>${esc(o.location)}</span><span>${esc(o.mode)}</span><span>${money(o.stipend)}</span></div><div class="row"><button class="primary apply" data-id="${o.id}" ${applied?'disabled':''}>${applied?'Applied':'Apply now'}</button><button class="secondary interview" data-id="${o.id}">Interview prep</button></div></article>`;}
function applications(){return hero('Your applications','One place to see where every opportunity stands.')+`<div class="timeline">${cache.applications.length?cache.applications.map(a=>`<div class="application"><div><b>${esc(a.title)}</b><span>${esc(a.company)}</span></div><strong>${esc(a.status)}</strong><small>${new Date(a.createdAt).toLocaleDateString()}</small></div>`).join(''):'<div class="empty">No applications yet. Apply from Discover Jobs.</div>'}</div>`;}
async function pulse(){if(!cache.pulse)cache.pulse=await api('/api/ai/skillpulse');const p=cache.pulse;return hero('SkillPulse','See where your skill set sits in the student talent market.')+`<div class="stats">${stat('Similar students',p.similarStudents,`within ${p.population} profiles`)}${stat('Market signals',(p.suggestedSkills||[]).length,'skills worth exploring')}</div><div class="grid-2">${card('Common skills',(p.commonSkills||[]).map(x=>`<div class="signal"><b>${esc(x.skill)}</b><span>${x.rarity}% rarity</span></div>`).join('')||'<div class="empty">Not enough data yet.</div>')}${card('Differentiating skills',(p.differentiators||[]).map(x=>`<div class="signal"><b>${esc(x.skill)}</b><span>${x.rarity}% rarity</span></div>`).join('')||'<div class="empty">Build a richer profile for this signal.</div>')}${card('Suggested skills',(p.suggestedSkills||[]).map(x=>`<div class="signal"><b>${esc(x.skill)}</b><span>${x.demand}% demand • ${x.rarity}% rarity</span></div>`).join('')||'<div class="empty">No suggestions yet.</div>')}</div>`;}
async function career(){if(!cache.career)cache.career=await api('/api/ai/career?role=software%20engineer');const c=cache.career;return hero('Career Path','Turn your current profile into a concrete roadmap.')+card('Software Engineer roadmap',`<div class="roadmap"><div><b>1</b><span>Current skills</span><p>${pills(c.currentSkills)}</p></div><div><b>2</b><span>Skill gaps</span><p>${pills(c.missingSkills)}</p></div><div><b>3</b><span>Build evidence</span><p>Use projects to demonstrate the missing skills, then apply.</p></div></div>`);}
async function interview(){const o=cache.opportunities[0];if(!o)return hero('Interview Prep','Add opportunities to unlock targeted practice.');const d=await api(`/api/ai/interview/${o.id}`);return hero(`Prepare for ${esc(o.title)}`,'Practice questions generated from the role and required skills.')+card('Question set',d.questions.map(q=>`<div class="question"><b>${q.id}.</b><span>${esc(q.question)}</span></div>`).join(''));}
function orgDashboard(){return hero('Talent, without the noise','Understand your student talent pool through aggregate skills and role signals.')+`<div class="stats">${stat('Opportunities',cache.opportunities.length,'published')}${stat('Tracked skills',cache.market?.skills?.length||0,'market')}${stat('Student pool',cache.market?.students||0,'aggregate only')}${stat('Openings',cache.market?.opportunities||0,'current')}</div>${card('AI Job Posting Builder',`<textarea id="job-text" placeholder="Looking for a Python/React intern in Bengaluru, hybrid, 3+ months experience…"></textarea><button id="analyze-job" class="primary">Extract requirements</button><div id="job-out"></div>`)}<div class="job-grid">${cache.opportunities.slice(0,4).map(jobCard).join('')}</div>`;}
function talent(){return hero('Talent Market','Aggregate-only visibility into student skills and role supply.')+card('Skill distribution',(cache.market?.skills||[]).slice(0,15).map(s=>`<div class="bar-row"><b>${esc(s.skill)}</b><div class="bar"><i style="width:${Math.max(5,Math.min(100,s.students/(cache.market.students||1)*100))}%"></i></div><span>${s.students} students</span></div>`).join(''));}
function post(){return hero('Post an opportunity','Describe the role in plain English and create a structured listing.')+card('Create posting',`<div class="form-grid"><input id="company" placeholder="Company"><input id="title" placeholder="Role title"><input id="location" placeholder="Location"><select id="post-mode"><option>Remote</option><option>Hybrid</option><option>On-site</option><option>Flexible</option></select><input id="stipend" placeholder="Stipend"><textarea id="description" class="span-2" placeholder="Describe responsibilities, required skills and experience…"></textarea></div><button id="create-job" class="primary">Create opportunity</button><div id="create-out"></div>`);}
function intel(){return hero('Market Intelligence','Compare the roles, skills, work modes and stipends visible in the current pool.')+card('Opportunity landscape',cache.opportunities.slice(0,10).map(o=>`<div class="intel"><div><b>${esc(o.company)}</b><span>${esc(o.title)}</span></div><span>${pills(o.skills)}</span><strong>${money(o.stipend)}</strong></div>`).join(''));}
async function render(){try{if(role==='student')await loadStudent();else await loadOrg();let c;if(role==='student'){c=page==='dashboard'?dashboard():page==='discover'?discover():page==='applications'?applications():page==='pulse'?await pulse():page==='career'?await career():await interview();}else{c=page==='dashboard'?orgDashboard():page==='talent'?talent():page==='post'?post():intel();}shell(c);bind();}catch(e){shell(`<div class="error"><h2>SkillBridge</h2><p>${esc(e.message)}</p><button class="primary" onclick="location.reload()">Reload</button></div>`);}}
function bind(){
  const profileBtn=document.getElementById('analyze-profile');if(profileBtn)profileBtn.onclick=async()=>{try{const r=await api('/api/ai/profile',{method:'POST',body:JSON.stringify({text:document.getElementById('profile-text').value})});document.getElementById('ai-out').innerHTML=`<div class="ai-result"><b>Extracted:</b> ${pills(r.skills)} <span>${esc((r.roles||[]).join(', '))}</span><button id="save-ai" class="secondary">Save to profile</button></div>`;document.getElementById('save-ai').onclick=async()=>{const p=cache.profile;await api(`/api/students/${p.id}`,{method:'PUT',body:JSON.stringify({...p,skills:r.skills,interests:[...(p.interests||[]),...(r.interests||[])],experienceMonths:Math.max(p.experienceMonths||0,r.experienceMonths||0)})});cache.pulse=null;render();};}catch(e){document.getElementById('ai-out').textContent=e.message;}};
  const search=document.getElementById('search');if(search)search.onclick=async()=>{const q=document.getElementById('q').value,mode=document.getElementById('mode').value;cache.opportunities=await api(`/api/opportunities?q=${encodeURIComponent(q)}&mode=${encodeURIComponent(mode)}`);shell(discover());bind();};
  document.querySelectorAll('.apply').forEach(b=>b.onclick=async()=>{await api('/api/applications',{method:'POST',body:JSON.stringify({opportunityId:Number(b.dataset.id)})});render();});
  document.querySelectorAll('.follow').forEach(b=>b.onclick=async()=>{await api('/api/follows',{method:'POST',body:JSON.stringify({company:b.dataset.company})});render();});
  document.querySelectorAll('.interview').forEach(b=>b.onclick=()=>{page='interview';render();});
  const analyzeJob=document.getElementById('analyze-job');if(analyzeJob)analyzeJob.onclick=async()=>{try{const r=await api('/api/ai/job',{method:'POST',body:JSON.stringify({text:document.getElementById('job-text').value})});document.getElementById('job-out').innerHTML=`<div class="ai-result"><b>Suggested:</b> ${esc((r.roles||[]).join(', ')||'General role')} ${pills(r.skills)} <span>${r.minExperienceMonths||0} months experience</span></div>`;}catch(e){document.getElementById('job-out').textContent=e.message;}};
  const createJob=document.getElementById('create-job');if(createJob)createJob.onclick=async()=>{try{await api('/api/opportunities',{method:'POST',body:JSON.stringify({company:company.value,title:title.value,location:location.value,mode:document.getElementById('post-mode').value,stipend:stipend.value,description:description.value})});document.getElementById('create-out').textContent='Opportunity created.';cache.opportunities=await api('/api/opportunities');}catch(e){document.getElementById('create-out').textContent=e.message;}};
}
render();
