const app=document.getElementById("app");
const USER=localStorage.getItem("skillbridge_user")||"demo-student";
let role=localStorage.getItem("skillbridge_role")||"student";
let page="dashboard";
const state={profile:null,jobs:[],matches:[],applications:[],follows:[],feed:null,recs:null,pulse:null,career:null,market:null,selected:null,filters:{}};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const pills=a=>(a||[]).map(x=>`<span class="pill">${esc(x)}</span>`).join("");
const money=v=>esc(v||"Not specified");
async function api(url,opt={}){const h=new Headers(opt.headers||{});h.set("X-Local-User",USER);h.set("X-Local-Role",role);if(opt.body&&!h.has("Content-Type"))h.set("Content-Type","application/json");const r=await fetch(url,{...opt,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d;}
function shell(html){const nav=role==="student"?["dashboard","discover","following","applications","pulse","career","interview"]:["dashboard","talent","post","intel"];const labels={dashboard:role==="student"?"Dashboard":"Overview",discover:"Discover Jobs",following:"Following",applications:"Applications",pulse:"SkillPulse",career:"Career Path",interview:"Interview Prep",talent:"Talent Market",post:"Post Opportunity",intel:"Market Intel"};app.innerHTML=`<div class="app-shell"><header class="topbar"><div class="brand"><div class="brand-mark">S</div><div><b>SkillBridge</b><small>Student Skill Matcher</small></div></div><nav>${nav.map(x=>`<button class="nav-btn ${page===x?'active':''}" data-page="${x}">${labels[x]}</button>`).join("")}</nav><div class="top-actions"><span class="role-badge">${role}</span><button id="switch" class="ghost">Switch role</button></div></header><main>${html}</main><footer>SkillBridge • local development mode</footer></div>`;document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{page=b.dataset.page;state.selected=null;render();});document.getElementById("switch").onclick=()=>{role=role==="student"?"organization":"student";localStorage.setItem("skillbridge_role",role);page="dashboard";render();};}
const card=(t,b)=>`<section class="card"><div class="card-head"><h3>${t}</h3></div>${b}</section>`;
const hero=(t,s)=>`<div class="hero"><span class="eyebrow">AI-POWERED CAREER PLATFORM</span><h1>${t}</h1><p>${s}</p></div>`;
const stat=(l,v,s="")=>`<div class="stat"><span>${l}</span><b>${esc(v)}</b><small>${s}</small></div>`;
async function loadStudent(){state.profile=(await api("/api/students"))[0];if(!state.profile)throw Error("No student profile");[state.jobs,state.applications,state.follows]=await Promise.all([api("/api/opportunities"),api("/api/applications"),api("/api/follows")]);state.matches=(await api(`/api/matches/${state.profile.id}`)).matches||[];}
async function loadOrg(){[state.jobs,state.market]=await Promise.all([api("/api/opportunities"),api("/api/market")]);}
function jobCard(o){const followed=state.follows.some(f=>f.company===o.company),applied=state.applications.find(a=>a.opportunityId===o.id);return `<article class="job-card"><div class="job-top"><span class="company">${esc(o.company)}</span><button class="icon-btn follow" data-company="${esc(o.company)}">${followed?"★":"☆"}</button></div><h3>${esc(o.title)}</h3><p>${esc(o.description)}</p><div>${pills(o.skills)}</div><div class="job-meta"><span>${esc(o.location)}</span><span>${esc(o.mode)}</span><span>${money(o.stipend)}</span></div><div class="row"><button class="secondary details" data-id="${o.id}">Details</button>${applied?`<span class="pill">${esc(applied.status)}</span>`:`<button class="primary apply" data-id="${o.id}">Apply</button>`}</div></article>`;}
function recommendationCard(m){const o=m.opportunity;return `<div class="match"><div><b>${esc(o.company)}</b><h4>${esc(o.title)}</h4><small>${esc(o.mode)} • ${esc(o.location)}</small><div>${pills(o.skills)}</div><small>${(m.personalizedReasons||m.reasons||[]).slice(0,2).map(esc).join(" • ")}</small></div><div class="score">${Math.round(m.score)}<small>% fit</small></div></div>`;}
async function dashboard(){if(!state.recs)state.recs=await api("/api/recommendations");const p=state.profile;return hero(`Build your next move, ${esc(p.name||"student")}.`,"Your recommendations learn from your skills, applications and followed companies.")+`<div class="stats">${stat("Profile skills",(p.skills||[]).length)}${stat("Recommendations",state.recs.matches.length)}${stat("Applications",state.applications.length)}${stat("Following",state.follows.length)}</div><div class="grid-2">${card("Personalized recommendations",state.recs.matches.slice(0,5).map(recommendationCard).join("")||"<div class='empty'>Build your profile to unlock recommendations.</div>")}${card("AI Profile Builder",`<p>Tell SkillBridge about yourself in normal language.</p><textarea id="profile-text" placeholder="I am a second-year CSE student who knows Python, React and SQL and want frontend or AI internships."></textarea><button id="analyze" class="primary">Analyze</button><div id="ai-out"></div>`)}</div>`;}
function discover(){return hero("Discover opportunities","Search roles, follow companies and get explainable recommendations.")+`<section class="card"><div class="filters"><input id="q" placeholder="Search role, company or skill"><select id="mode"><option value="">Any mode</option><option>Remote</option><option>Hybrid</option><option>On-site</option><option>Flexible</option></select><input id="skill" placeholder="Skill"><button id="search" class="primary">Search</button></div></section><div class="job-grid">${state.jobs.filter(o=>{const q=(document.getElementById("q")?.value||state.filters.q||"").toLowerCase();return !q||`${o.company} ${o.title} ${o.description} ${(o.skills||[]).join(" ")}`.toLowerCase().includes(q)}).filter(o=>!state.filters.mode||o.mode===state.filters.mode).filter(o=>!state.filters.skill||(o.skills||[]).includes(state.filters.skill)).map(jobCard).join("")||"<div class='empty'>No matching opportunities.</div>"}</div>`;}
async function following(){if(!state.feed)state.feed=await api("/api/feed");return hero("Following","Company updates, hiring activity and opportunities from companies you follow.")+card("Your companies",state.feed.following.length?state.feed.following.map(c=>`<span class="pill">★ ${esc(c)}</span>`).join(""):"<div class='empty'>Follow a company from Discover Jobs to build your feed.</div>")+card("Company feed",state.feed.items.map(c=>`<article class="feed-item"><div class="row"><div><b>${esc(c.company)}</b><p>${esc(c.summary)}</p></div></div>${c.roles.map(o=>`<div class="signal"><div><b>${esc(o.title)}</b><span>${esc(o.location)} • ${esc(o.mode)} • ${money(o.stipend)}</span></div><button class="secondary details" data-id="${o.id}">Open</button></div>`).join("")}</article>`).join("")||"<div class='empty'>Nothing in your feed yet.</div>");}
function applications(){const stages=["Saved","Applied","Shortlisted","Interview","Offer","Rejected","Withdrawn"];return hero("Application Tracker","Keep every opportunity moving with notes and status updates.")+`<div class="app-board">${stages.map(s=>`<section class="app-column"><div class="column-head"><b>${s}</b><span>${state.applications.filter(a=>a.status===s).length}</span></div>${state.applications.filter(a=>a.status===s).map(a=>`<article class="app-item"><b>${esc(a.title)}</b><span>${esc(a.company)}</span><small>${esc(a.note||"No note")}</small><div class="row"><button class="secondary app-open" data-id="${a.opportunityId}">Open</button>${!["Offer","Rejected","Withdrawn"].includes(s)?`<button class="primary advance" data-id="${a.id}" data-status="${s==="Saved"?"Applied":s==="Applied"?"Shortlisted":s==="Shortlisted"?"Interview":"Offer"}">Next</button>`:""}</div></article>`).join("")||"<div class='empty'>Empty</div>"}</section>`).join("")}</div>`;}
async function pulse(){if(!state.pulse)state.pulse=await api("/api/ai/skillpulse");const p=state.pulse;return hero("SkillPulse","Understand your relative skill profile and market signals.")+`<div class="stats">${stat("Similar students",p.similarStudents)}${stat("Differentiators",(p.differentiators||[]).length)}${stat("Suggested skills",(p.suggestedSkills||[]).length)}</div><div class="grid-2">${card("Common skills",(p.commonSkills||[]).map(x=>`<div class="signal"><b>${esc(x.skill)}</b><span>${x.rarity}% rarity</span></div>`).join("")||"<div class='empty'>No data.</div>")}${card("Suggested next skills",(p.suggestedSkills||[]).map(x=>`<div class="signal"><b>${esc(x.skill)}</b><span>${x.demand}% demand • ${x.rarity}% rarity</span></div>`).join("")||"<div class='empty'>No suggestions.</div>")}</div>`;}
async function career(){if(!state.career)state.career=await api("/api/ai/career?role=software%20engineer");return hero("Career Path","Translate your current profile into a practical roadmap.")+card("Software Engineer",`<div class="roadmap"><div><b>1</b><span>Current</span><p>${pills(state.career.currentSkills)}</p></div><div><b>2</b><span>Missing</span><p>${pills(state.career.missingSkills)}</p></div><div><b>3</b><span>Evidence</span><p>Build projects that demonstrate the missing skills.</p></div></div>`);}
async function interview(){const o=state.jobs[0];if(!o)return hero("Interview Prep","No jobs available yet.");const d=await api(`/api/ai/interview/${o.id}`);return hero(`Prepare for ${esc(o.title)}`,"Questions are generated from the role requirements and your profile.")+card("Practice",d.questions.map(q=>`<div class="question"><b>${q.id}.</b><span>${esc(q.question)}</span></div>`).join(""));}
function talent(){return hero("Talent Market","Aggregate-only student skill and role supply.")+card("Skill distribution",(state.market?.skills||[]).slice(0,15).map(s=>`<div class="bar-row"><b>${esc(s.skill)}</b><div class="bar"><i style="width:${Math.max(5,Math.min(100,s.students/(state.market.students||1)*100))}%"></i></div><span>${s.students} students</span></div>`).join(""));}
function post(){return hero("Post an opportunity","Describe the role and let the local AI parser structure it.")+card("New opportunity",`<div class="form-grid"><input id="company" placeholder="Company"><input id="title" placeholder="Role title"><input id="location" placeholder="Location"><input id="industry" placeholder="Industry"><select id="pmode"><option>Remote</option><option>Hybrid</option><option>On-site</option><option>Flexible</option></select><input id="stipend" placeholder="Stipend"><input id="years" placeholder="Target years: 2,3"><textarea id="desc" class="span-2" placeholder="Responsibilities, skills, experience..."></textarea></div><button id="create" class="primary">Publish</button><div id="post-out"></div>`);}
function intel(){return hero("Market Intelligence","See the current visible role landscape.")+card("Open roles",state.jobs.map(o=>`<div class="intel"><div><b>${esc(o.company)}</b><span>${esc(o.title)}</span></div><strong>${money(o.stipend)}</strong></div>`).join(""));}
function details(){const o=state.selected;if(!o)return discover();const m=state.matches.find(x=>x.opportunity?.id===o.id),a=state.applications.find(x=>x.opportunityId===o.id);return hero(esc(o.title),`${esc(o.company)} • ${esc(o.location)} • ${esc(o.mode)}`)+`<div class="grid-2">${card("Opportunity",`<p>${esc(o.description)}</p><div>${pills(o.skills)}</div><p>${money(o.stipend)}</p>`)}${card("Your fit",m?`<div class="big-fit">${Math.round(m.score)}%</div><p>${(m.reasons||[]).map(esc).join(" • ")}</p>`:"No score")}${a?card("Application",`<select id="status">${["Saved","Applied","Shortlisted","Interview","Offer","Rejected","Withdrawn"].map(s=>`<option ${a.status===s?"selected":""}>${s}</option>`).join("")}</select><textarea id="note">${esc(a.note||"")}</textarea><button id="save-app" class="primary" data-id="${a.id}">Save</button>`:`<button class="primary apply" data-id="${o.id}">Apply now</button>`}</div>`;}
async function render(){try{if(role==="student")await loadStudent();else await loadOrg();let html;if(state.selected)html=details();else if(page==="dashboard")html=role==="student"?await dashboard():hero("Talent, without the noise",`${state.market?.students||0} students • ${state.jobs.length} visible opportunities`);else if(page==="discover")html=discover();else if(page==="following")html=await following();else if(page==="applications")html=applications();else if(page==="pulse")html=await pulse();else if(page==="career")html=await career();else if(page==="interview")html=await interview();else if(page==="talent")html=talent();else if(page==="post")html=post();else html=intel();shell(html);bind();}catch(e){shell(`<div class="error">${esc(e.message)}</div>`);}}
function bind(){document.getElementById("search")?.addEventListener("click",()=>{state.filters={q:document.getElementById("q").value.trim(),mode:document.getElementById("mode").value,skill:document.getElementById("skill").value.trim().toLowerCase()};render();});document.querySelectorAll(".details,.app-open").forEach(b=>b.onclick=()=>{state.selected=state.jobs.find(o=>o.id===Number(b.dataset.id));render();});document.querySelectorAll(".apply").forEach(b=>b.onclick=async()=>{await api("/api/applications",{method:"POST",body:JSON.stringify({opportunityId:Number(b.dataset.id)})});await api("/api/activity",{method:"POST",body:JSON.stringify({type:"apply",opportunityId:Number(b.dataset.id),company:state.jobs.find(o=>o.id===Number(b.dataset.id))?.company})});render();});document.querySelectorAll(".follow").forEach(b=>b.onclick=async()=>{await api("/api/follows",{method:"POST",body:JSON.stringify({company:b.dataset.company})});state.feed=null;state.recs=null;render();});document.querySelectorAll(".advance").forEach(b=>b.onclick=async()=>{await api(`/api/applications/${encodeURIComponent(b.dataset.id)}`,{method:"PUT",body:JSON.stringify({status:b.dataset.status})});render();});document.getElementById("analyze")?.addEventListener("click",async()=>{const r=await api("/api/ai/profile",{method:"POST",body:JSON.stringify({text:document.getElementById("profile-text").value})});document.getElementById("ai-out").innerHTML=card("Extracted profile",`<p>${pills(r.skills)}</p><p>${pills(r.interests)}</p><small>${esc(r.headline||"")}</small>`);});document.getElementById("save-app")?.addEventListener("click",async b=>{await api(`/api/applications/${encodeURIComponent(b.target.dataset.id)}`,{method:"PUT",body:JSON.stringify({status:document.getElementById("status").value,note:document.getElementById("note").value})});render();});document.getElementById("create")?.addEventListener("click",async()=>{const years=(document.getElementById("years").value.match(/\d+/g)||[]).map(Number);const d={company:document.getElementById("company").value,title:document.getElementById("title").value,location:document.getElementById("location").value,industry:document.getElementById("industry").value,mode:document.getElementById("pmode").value,stipend:document.getElementById("stipend").value,targetYears:years,description:document.getElementById("desc").value};const r=await api("/api/opportunities",{method:"POST",body:JSON.stringify(d)});document.getElementById("post-out").innerHTML=`<div class="ai-result">Published ${esc(r.title)} with ${r.skills.length} extracted skills.</div>`;loadOrg();});}
render();
