import { APPLICATION_STATUSES } from "/shared/constants.js";

const app = document.getElementById("app");
let config;
let firebase = null;
let currentUser = null;
let role = "student";
let page = "dashboard";
const state = { profile: null, jobs: [], applications: [], follows: [], recs: null, pulse: null, career: null, market: null, candidates: null, selected: null, filters: { q: "", mode: "", skill: "", year: "" }, intel: "" };

const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[c]));
const pills = (values) => (values || []).map((v) => `<span class="pill">${esc(v)}</span>`).join("");
const money = (value) => esc(value || "Not specified");
const card = (title, body) => `<section class="card"><div class="card-head"><h3>${title}</h3></div>${body}</section>`;
const hero = (title, subtitle) => `<div class="hero"><span class="eyebrow">AI-POWERED CAREER PLATFORM</span><h1>${title}</h1><p>${subtitle}</p></div>`;
const stat = (label, value, note = "") => `<div class="stat"><span>${esc(label)}</span><b>${esc(value)}</b><small>${esc(note)}</small></div>`;

async function getConfig() { if (config) return config; const response = await fetch("/api/health", { cache: "no-store" }); if (!response.ok) throw new Error("Backend health check failed"); config = await response.json(); return config; }
async function api(url, options = {}) {
  const headers = new Headers(options.headers || {});
  if ((await getConfig()).localAuth) {
    headers.set("X-Local-User", role === "organization" ? "demo-org" : "demo-student");
    headers.set("X-Local-Role", role);
  } else {
    if (!currentUser) throw new Error("Please sign in first.");
    headers.set("Authorization", `Bearer ${await currentUser.getIdToken()}`);
  }
  if (options.body && !headers.has("Content-Type")) headers.set("Content-Type", "application/json");
  const response = await fetch(url, { ...options, headers });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`);
  return data;
}

function shell(content) {
  const links = (role === "student" ? [["dashboard","Dashboard"],["discover","Discover Jobs"],["following","Following"],["applications","Applications"],["pulse","SkillPulse"],["career","Career Path"],["interview","Interview Prep"],["profile","My Profile"]] : [["dashboard","Overview"],["talent","Talent Market"],["post","Post Opportunity"],["intel","Market Intel"]]).map(([key, label]) => `<button class="nav-btn ${page === key ? "active" : ""}" data-page="${key}">${label}</button>`).join("");
  app.innerHTML = `<div class="app-shell"><header class="topbar"><div class="brand"><div class="brand-mark">S</div><div><b>SkillBridge</b><small>Student Skill Matcher</small></div></div><nav>${links}</nav><div class="top-actions"><span class="role-badge">${esc(role)}</span>${config?.localAuth ? `<button id="switch" class="ghost">Switch role</button>` : `<button id="logout" class="ghost">Sign out</button>`}</div></header><main>${content}</main><footer>SkillBridge • ${config?.localAuth ? "local development mode" : "authenticated mode"}</footer></div>`;
  document.querySelectorAll("[data-page]").forEach((button) => button.addEventListener("click", () => { page = button.dataset.page; state.selected = null; render(); }));
  document.getElementById("switch")?.addEventListener("click", () => { role = role === "student" ? "organization" : "student"; page = "dashboard"; state.selected = null; state.recs = null; state.market = null; render(); });
  document.getElementById("logout")?.addEventListener("click", async () => { if (firebase && currentUser) await firebase.signOut(firebase.auth); location.reload(); });
}

async function loadStudent() { state.profile = await api("/api/profile"); [state.jobs, state.applications, state.follows] = await Promise.all([api("/api/opportunities"), api("/api/applications"), api("/api/follows")]); }
async function loadOrg() { [state.jobs, state.market] = await Promise.all([api("/api/opportunities"), api("/api/market")]); }

function jobCard(job) { const followed = state.follows.some((f) => String(f.company || "").toLowerCase() === String(job.company || "").toLowerCase()); const applied = state.applications.find((a) => String(a.opportunityId) === String(job.id)); return `<article class="job-card"><div class="job-top"><span class="company">${esc(job.company)}</span><button class="icon-btn follow" data-company="${esc(job.company)}">${followed ? "★" : "☆"}</button></div><h3>${esc(job.title)}</h3><p>${esc(job.description)}</p><div>${pills(job.skills)}</div><div class="job-meta"><span>${esc(job.location)}</span><span>${esc(job.mode)}</span><span>${money(job.stipend)}</span></div><div class="row"><button class="secondary details" data-id="${esc(job.id)}">Details</button>${applied ? `<span class="pill">${esc(applied.status)}</span>` : `<button class="primary apply" data-id="${esc(job.id)}">Apply</button>`}</div></article>`; }
function matchCard(match) { const job = match.opportunity; return `<div class="match"><div><b>${esc(job.company)}</b><h4>${esc(job.title)}</h4><small>${esc(job.mode)} • ${esc(job.location)}</small><div>${pills(job.skills)}</div><small>${(match.personalizedReasons || match.reasons || []).slice(0, 3).map(esc).join(" • ")}</small></div><div class="score">${Math.round(match.score || 0)}<small>% fit</small></div></div>`; }

async function dashboard() { if (!state.recs) state.recs = await api("/api/recommendations"); const p = state.profile; return hero(`Build your next move, ${esc(p.name || "student")}.`, "Explainable matching uses skills, evidence, role alignment and recent activity.") + `<div class="stats">${stat("Profile skills", (p.skills || []).length)}${stat("Recommendations", state.recs.matches.length)}${stat("Applications", state.applications.length)}${stat("Following", state.follows.length)}</div><div class="grid-2">${card("Personalized recommendations", state.recs.matches.slice(0, 5).map(matchCard).join("") || `<div class="empty">Complete your profile to improve matching.</div>`)}${card("AI Profile Builder", `<p>Describe yourself naturally and extract useful profile signals.</p><textarea id="ai-text" placeholder="Second-year CSE student with React and Python, wants frontend roles, 8 months experience."></textarea><button id="ai-analyze" class="primary">Analyze</button><div id="ai-output"></div>`)}${card("Recruiter discovery", `<p>Only verified organizations can access profiles that explicitly opt in.</p><label><input id="candidate-opt" type="checkbox" ${p.candidateOptIn ? "checked" : ""}> Available to verified recruiters</label>`)}${card("Market contribution", `<p>Opt in to anonymous aggregate market analytics used by SkillPulse.</p><label><input id="market-opt" type="checkbox" ${p.marketOptIn ? "checked" : ""}> Include me in aggregate analytics</label>`)}</div>`; }

function discover() { const jobs = state.jobs.filter((job) => { const q = (state.filters.q || "").toLowerCase(); const hay = [job.company, job.title, job.description, ...(job.skills || [])].join(" ").toLowerCase(); return (!q || hay.includes(q)) && (!state.filters.mode || job.mode === state.filters.mode) && (!state.filters.skill || (job.skills || []).includes(state.filters.skill)) && (!state.filters.year || (job.targetYears || []).map(String).includes(String(state.filters.year))); }); return hero("Discover opportunities", "Search roles, skills, companies, work modes and academic year.") + `<section class="card"><div class="filter-grid"><input id="q" value="${esc(state.filters.q)}" placeholder="Search role, company or skill"><select id="mode"><option value="">Any mode</option>${["Remote","Hybrid","On-site","Flexible"].map((x) => `<option value="${x}" ${state.filters.mode === x ? "selected" : ""}>${x}</option>`).join("")}</select><input id="skill" value="${esc(state.filters.skill)}" placeholder="Skill"><select id="year"><option value="">Any year</option>${[1,2,3,4].map((x) => `<option value="${x}" ${String(state.filters.year) === String(x) ? "selected" : ""}>Year ${x}</option>`).join("")}</select><button id="search" class="primary">Search</button></div></section><div class="job-grid">${jobs.map(jobCard).join("") || `<div class="empty">No opportunities match those filters.</div>`}</div>`; }
async function following() { const feed = await api("/api/feed"); return hero("Following", "Company updates and active openings from companies you follow.") + card("Your companies", feed.following.length ? feed.following.map((x) => `<span class="pill">★ ${esc(x)}</span>`).join("") : `<div class="empty">Follow a company from Discover Jobs.</div>`) + card("Company feed", feed.items.map((company) => `<article class="feed-item"><b>${esc(company.company)}</b><p>${esc(company.summary)}</p>${company.roles.map((job) => `<div class="signal"><div><b>${esc(job.title)}</b><span>${esc(job.location)} • ${esc(job.mode)} • ${money(job.stipend)}</span></div><button class="secondary details" data-id="${esc(job.id)}">Open</button></div>`).join("")}</article>`).join("") || `<div class="empty">Nothing in your feed yet.</div>`); }
function applications() { const stages = APPLICATION_STATUSES; return hero("Application Tracker", "Move applications through server-validated stages.") + `<div class="app-board">${stages.map((stage) => `<section class="app-column"><div class="column-head"><b>${stage}</b><span>${state.applications.filter((a) => a.status === stage).length}</span></div>${state.applications.filter((a) => a.status === stage).map((a) => `<article class="app-item"><b>${esc(a.title)}</b><span>${esc(a.company)}</span><small>${esc(a.note || "No note")}</small><div class="row"><button class="secondary app-open" data-id="${esc(a.opportunityId)}">Open</button></div></article>`).join("") || `<div class="empty">Empty</div>`}</section>`).join("")}</div>`; }
async function pulse() { state.pulse = await api("/api/ai/skillpulse"); const p = state.pulse; return hero("SkillPulse", "Aggregate skill signals from consenting profiles.") + `<div class="stats">${stat("Similar students", p.similarStudents)}${stat("Differentiators", (p.differentiators || []).length)}${stat("Suggested skills", (p.suggestedSkills || []).length)}</div><div class="grid-2">${card("Common skills", (p.commonSkills || []).map((x) => `<div class="signal"><b>${esc(x.skill)}</b><span>${x.rarity}% rarity</span></div>`).join("") || `<div class="empty">No data.</div>`)}${card("Suggested next skills", (p.suggestedSkills || []).map((x) => `<div class="signal"><b>${esc(x.skill)}</b><span>${x.demand}% demand • ${x.rarity}% rarity</span></div>`).join("") || `<div class="empty">No suggestions.</div>`)}</div>`; }
async function career() { state.career = await api("/api/ai/career?role=software%20engineer"); return hero("Career Path", "Translate your profile into a practical roadmap.") + card("Software Engineer", `<div class="roadmap"><div><b>1</b><span>Current</span><p>${pills(state.career.currentSkills)}</p></div><div><b>2</b><span>Missing</span><p>${pills(state.career.missingSkills)}</p></div><div><b>3</b><span>Evidence</span><p>Build projects that demonstrate the missing skills.</p></div></div>`); }
async function interview() { const job = state.jobs[0]; if (!job) return hero("Interview Prep", "No opportunities available yet."); const data = await api(`/api/ai/interview/${encodeURIComponent(job.id)}`); return hero(`Prepare for ${esc(job.title)}`, "Questions are generated from the role requirements and your profile.") + card("Practice", (data.questions || []).map((q) => `<div class="question"><b>${q.id}.</b><span>${esc(q.question)}</span></div>`).join("") || `<div class="empty">No questions generated.</div>`); }

async function profilePage() { const p = state.profile; const details = (p.skillDetails || []).map((x) => `${x.name} | ${x.level || "comfortable"} | ${x.learnedFrom || "self"}`).join("\n"); return hero("My Profile", "Give the matcher evidence, not just keywords.") + `<form id="profile-form"><div class="grid-2">${card("Basics", `<div class="form-grid"><input id="p-name" value="${esc(p.name)}" placeholder="Name"><input id="p-headline" value="${esc(p.headline)}" placeholder="Headline"><input id="p-college" value="${esc(p.college)}" placeholder="College"><input id="p-degree" value="${esc(p.degree)}" placeholder="Degree"><input id="p-branch" value="${esc(p.branch)}" placeholder="Branch"><input id="p-year" type="number" min="1" max="6" value="${esc(p.year || 1)}"><input id="p-grad" type="number" min="2024" value="${esc(p.graduationYear)}"><input id="p-mode" value="${esc(p.preferredMode)}" placeholder="Preferred mode"><textarea id="p-bio" class="span-2">${esc(p.bio)}</textarea></div>`)}${card("Career preferences", `<label>Skills</label><input id="p-skills" value="${esc((p.skills || []).join(", "))}"><label>Interests</label><input id="p-interests" value="${esc((p.interests || []).join(", "))}"><label>Target roles</label><input id="p-roles" value="${esc((p.roles || []).join(", "))}"><label>Preferred locations</label><input id="p-locations" value="${esc((p.preferredLocations || []).join(", "))}"><label>Experience months</label><input id="p-exp" type="number" min="0" value="${esc(p.experienceMonths || 0)}"></section>`)} </div>${card("Skill evidence", `<p>One per line: skill | level | learned from</p><textarea id="p-details" class="ai-profile-input">${esc(details)}</textarea>`)}<div class="row"><button class="primary" type="submit">Save profile</button><span id="p-saved" class="pill"></span></div></form>`; }

async function talent() { if (!state.market) state.market = await api("/api/market"); const total = Math.max(1, state.market.students || 1); return hero("Talent Market", "Aggregate market data plus a consent-gated candidate pool.") + `<div class="stats">${stat("Consenting students", state.market.students)}${stat("Open opportunities", state.market.opportunities)}${stat("Tracked skills", state.market.skills.length)}${stat("Roles", state.market.roles.length)}</div>${card("Skill distribution", state.market.skills.slice(0, 15).map((item) => `<div class="bar-row"><b>${esc(item.skill)}</b><div class="bar"><i style="width:${Math.max(5, Math.min(100, item.students / total * 100))}%"></i></div><span>${item.students} students • ${item.openings} openings</span></div>`).join("") || `<div class="empty">No market data.</div>`)}${card("Opt-in candidate discovery", `<div class="filter-grid"><input id="c-skill" placeholder="Skill"><input id="c-role" placeholder="Role"><input id="c-year" placeholder="Year"><button id="c-search" class="primary">Find candidates</button></div><div id="candidate-list">${(state.candidates || []).map(candidateCard).join("") || `<div class="empty">Run a filter. Only explicitly opted-in profiles appear.</div>`}</div>`)}`; }
function candidateCard(c) { return `<article class="candidate-card"><b>${esc(c.name)}</b><span>${esc(c.headline || "")} • ${esc(c.college || "")}</span><div>${pills(c.roles)}</div><div>${pills(c.skills)}</div><small>Year ${esc(c.year || "-")} • ${esc(c.preferredMode || "Flexible")}</small></article>`; }
function post() { return hero("Post an opportunity", "Describe the role and let the local parser structure it.") + card("New opportunity", `<div class="form-grid"><input id="o-company" placeholder="Company"><input id="o-title" placeholder="Role title"><input id="o-location" placeholder="Location"><select id="o-mode"><option>Remote</option><option>Hybrid</option><option>On-site</option><option>Flexible</option></select><input id="o-stipend" placeholder="Stipend"><input id="o-years" placeholder="Target years: 2,3"><textarea id="o-desc" class="span-2" placeholder="Responsibilities, skills, experience..."></textarea></div><button id="o-publish" class="primary">Publish</button><div id="o-out"></div>`); }
async function intel() { const data = await api(`/api/company-intel?q=${encodeURIComponent(state.intel)}`); return hero("Market Intelligence", "Structured role and stipend signals by company.") + `<section class="card"><div class="filters"><input id="intel-q" value="${esc(state.intel)}" placeholder="Company or skill"><button id="intel-search" class="primary">Analyze</button></div></section><div class="intel-grid">${data.companies.map((company) => `<article class="intel-card"><b>${esc(company.company)}</b><span>${company.openings} openings</span><p>${company.roles.map(esc).join(" • ")}</p><div>${company.topSkills.map((x) => `<span class="pill">${esc(x.skill)} × ${esc(x.count)}</span>`).join("")}</div>${company.stipend ? `<small>${esc(company.stipend.currency)} ${company.stipend.min.toLocaleString()} – ${company.stipend.max.toLocaleString()} • avg ${company.stipend.average.toLocaleString()}</small>` : ""}</article>`).join("") || `<div class="empty">No intelligence signals found.</div>`}</div>`; }
function details() { const job = state.selected; const match = state.recs?.matches?.find((x) => String(x.opportunity?.id) === String(job.id)); const application = state.applications.find((x) => String(x.opportunityId) === String(job.id)); return hero(esc(job.title), `${esc(job.company)} • ${esc(job.location)} • ${esc(job.mode)}`) + `<div class="grid-2">${card("Opportunity", `<p>${esc(job.description)}</p><div>${pills(job.skills)}</div><p>${money(job.stipend)}</p>`)}${card("Your fit", match ? `<div class="big-fit">${Math.round(match.score)}%</div><p>${(match.reasons || []).map(esc).join(" • ")}</p>` : `<p>Recommendation details will appear on the dashboard.</p>`)}${application ? card("Application", `<select id="detail-status">${APPLICATION_STATUSES.map((s) => `<option ${application.status === s ? "selected" : ""}>${s}</option>`).join("")}</select><textarea id="detail-note">${esc(application.note || "")}</textarea><button id="detail-save" class="primary" data-id="${esc(application.id)}">Save</button>`) : `<button class="primary apply" data-id="${esc(job.id)}">Apply now</button>`}</div>`; }

function bind() {
  document.getElementById("search")?.addEventListener("click", () => { state.filters = { q: document.getElementById("q").value.trim(), mode: document.getElementById("mode").value, skill: document.getElementById("skill").value.trim().toLowerCase(), year: document.getElementById("year").value }; render(); });
  document.querySelectorAll(".details,.app-open").forEach((b) => b.onclick = () => { state.selected = state.jobs.find((j) => String(j.id) === String(b.dataset.id)); render(); });
  document.querySelectorAll(".apply").forEach((b) => b.onclick = async () => { await api("/api/applications", { method: "POST", body: JSON.stringify({ opportunityId: b.dataset.id }) }); state.selected = null; await loadStudent(); render(); });
  document.querySelectorAll(".follow").forEach((b) => b.onclick = async () => { await api("/api/follows", { method: "POST", body: JSON.stringify({ company: b.dataset.company }) }); await loadStudent(); render(); });
  document.getElementById("ai-analyze")?.addEventListener("click", async () => { const r = await api("/api/ai/profile", { method: "POST", body: JSON.stringify({ text: document.getElementById("ai-text").value }) }); document.getElementById("ai-output").innerHTML = `<div class="ai-result"><b>Extracted profile</b><p>${pills(r.skills)}</p><p>${pills(r.roles)}</p><small>${esc(r.experienceMonths)} months experience signal</small></div>`; });
  document.getElementById("candidate-opt")?.addEventListener("change", async (e) => { await api("/api/profile/candidate-opt-in", { method: "PUT", body: JSON.stringify({ candidateOptIn: e.target.checked }) }); });
  document.getElementById("market-opt")?.addEventListener("change", async (e) => { await api("/api/profile/market-opt-in", { method: "PUT", body: JSON.stringify({ marketOptIn: e.target.checked }) }); });
  document.getElementById("c-search")?.addEventListener("click", async () => { const params = new URLSearchParams(); if (document.getElementById("c-skill").value) params.set("skill", document.getElementById("c-skill").value); if (document.getElementById("c-role").value) params.set("role", document.getElementById("c-role").value); if (document.getElementById("c-year").value) params.set("year", document.getElementById("c-year").value); state.candidates = await api(`/api/talent/candidates?${params}`); document.getElementById("candidate-list").innerHTML = state.candidates.map(candidateCard).join("") || `<div class="empty">No opted-in candidates match.</div>`; });
  document.getElementById("o-publish")?.addEventListener("click", async () => { const years = (document.getElementById("o-years").value.match(/\d+/g) || []).map(Number); const data = { company: document.getElementById("o-company").value, title: document.getElementById("o-title").value, location: document.getElementById("o-location").value, mode: document.getElementById("o-mode").value, stipend: document.getElementById("o-stipend").value, targetYears: years, description: document.getElementById("o-desc").value }; const r = await api("/api/opportunities", { method: "POST", body: JSON.stringify(data) }); document.getElementById("o-out").innerHTML = `<div class="ai-result">Published ${esc(r.title)} with ${r.skills.length} normalized skills.</div>`; state.jobs = await api("/api/opportunities"); });
  document.getElementById("intel-search")?.addEventListener("click", () => { state.intel = document.getElementById("intel-q").value.trim(); render(); });
  document.getElementById("profile-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const lines = (id, mapper) => document.getElementById(id).value.split("\n").map((x) => x.trim()).filter(Boolean).map(mapper); const payload = { name: document.getElementById("p-name").value, headline: document.getElementById("p-headline").value, college: document.getElementById("p-college").value, degree: document.getElementById("p-degree").value, branch: document.getElementById("p-branch").value, year: Number(document.getElementById("p-year").value) || 1, graduationYear: Number(document.getElementById("p-grad").value) || "", preferredMode: document.getElementById("p-mode").value, bio: document.getElementById("p-bio").value, skills: document.getElementById("p-skills").value.split(","), interests: document.getElementById("p-interests").value.split(","), roles: document.getElementById("p-roles").value.split(","), preferredLocations: document.getElementById("p-locations").value.split(","), experienceMonths: Number(document.getElementById("p-exp").value) || 0, skillDetails: lines("p-details", (x) => { const [name, level = "comfortable", learnedFrom = "self"] = x.split("|").map((v) => v.trim()); return { name, level, learnedFrom }; }), onboardingComplete: true }; state.profile = await api("/api/profile", { method: "PUT", body: JSON.stringify(payload) }); document.getElementById("p-saved").textContent = "Saved"; });
  document.getElementById("detail-save")?.addEventListener("click", async (e) => { await api(`/api/applications/${encodeURIComponent(e.target.dataset.id)}`, { method: "PUT", body: JSON.stringify({ status: document.getElementById("detail-status").value, note: document.getElementById("detail-note").value }) }); await loadStudent(); render(); });
}

async function render() { try { if (!config) await getConfig(); if (role === "student") await loadStudent(); else await loadOrg(); let content; if (state.selected) content = details(); else if (page === "dashboard") content = role === "student" ? await dashboard() : hero("Talent, without the noise", `${state.market?.students || 0} consenting students • ${state.jobs.length} visible opportunities`); else if (page === "discover") content = discover(); else if (page === "following") content = await following(); else if (page === "applications") content = applications(); else if (page === "pulse") content = await pulse(); else if (page === "career") content = await career(); else if (page === "interview") content = await interview(); else if (page === "profile") content = await profilePage(); else if (page === "talent") content = await talent(); else if (page === "post") content = post(); else content = await intel(); shell(content); bind(); } catch (error) { app.innerHTML = `<div class="error">${esc(error.message)}</div>`; } }

async function loginScreen() { app.innerHTML = `<div class="login-shell"><div class="login-card"><div class="brand-mark">S</div><h1>Welcome to SkillBridge</h1><p>Sign in with Firebase to continue.</p><input id="login-email" type="email" placeholder="Email"><input id="login-password" type="password" placeholder="Password"><div class="row"><button id="login" class="primary">Sign in</button><button id="signup" class="secondary">Create account</button></div><div id="login-error" class="error"></div></div></div>`; const fail = (error) => { document.getElementById("login-error").textContent = error.message; }; document.getElementById("login").onclick = async () => { try { await firebase.signInWithEmailAndPassword(firebase.auth, document.getElementById("login-email").value.trim(), document.getElementById("login-password").value); location.reload(); } catch (e) { fail(e); } }; document.getElementById("signup").onclick = async () => { try { await firebase.createUserWithEmailAndPassword(firebase.auth, document.getElementById("login-email").value.trim(), document.getElementById("login-password").value); location.reload(); } catch (e) { fail(e); } }; }

async function boot() { config = await getConfig(); if (!config.localAuth) { firebase = await import("./firebase.js"); currentUser = firebase.auth.currentUser; if (!currentUser) return loginScreen(); } await render(); }
boot();
