import { normalizeList, normalizeRole } from "./taxonomy.js";

const ago = (days, hours = 0) => new Date(Date.now() - ((days * 24 + hours) * 60 * 60 * 1000)).toISOString();
const skills = (values) => normalizeList(values);
const roles = (values) => normalizeList(values, normalizeRole);

export const demoSeed = {
  students: [
    {
      id: "stu-demo-5", uid: "demo-student-5", name: "Ishita Rao", headline: "Frontend builder focused on accessible products", skills: skills(["javascript", "react", "ui/ux", "git", "api"]), interests: ["product", "design", "startups"], experienceMonths: 7, preferredMode: "Hybrid", preferredLocations: ["bengaluru", "remote"], bio: "Builds clean interfaces and prototypes product ideas quickly.", year: 3, college: "BMS College of Engineering", degree: "B.Tech", branch: "Computer Science Engineering", graduationYear: 2027, roles: roles(["frontend", "ui/ux designer"]), candidateOptIn: true, marketOptIn: true, projects: [{ title: "Campus Cart", description: "React marketplace prototype with reusable UI components", technologies: skills(["react", "javascript", "ui/ux"]) }], experience: [{ title: "Frontend Intern", description: "Built responsive React screens for an edtech prototype", months: 7 }], skillDetails: [{ name: "javascript", level: "comfortable", learnedFrom: "projects" }, { name: "react", level: "comfortable", learnedFrom: "internship" }], onboardingComplete: true, createdAt: ago(40), updatedAt: ago(1)
    },
    {
      id: "stu-demo-6", uid: "demo-student-6", name: "Rohan Kulkarni", headline: "Python + data analytics student", skills: skills(["python", "sql", "data analysis", "excel", "git"]), interests: ["analytics", "business", "ai"], experienceMonths: 10, preferredMode: "Remote", preferredLocations: ["remote", "bengaluru"], bio: "Enjoys turning messy datasets into clear dashboards and insights.", year: 3, college: "PES University", degree: "B.Tech", branch: "Computer Science", graduationYear: 2027, roles: roles(["data analyst"]), candidateOptIn: true, marketOptIn: true, projects: [{ title: "Retail Insights", description: "SQL + Python analysis of sales trends and customer segments", technologies: skills(["python", "sql", "data analysis"]) }], experience: [{ title: "Data Intern", description: "Automated weekly reporting with Python and SQL", months: 10 }], skillDetails: [{ name: "python", level: "comfortable", learnedFrom: "projects" }, { name: "sql", level: "advanced", learnedFrom: "internship" }], onboardingComplete: true, createdAt: ago(38), updatedAt: ago(2)
    },
    {
      id: "stu-demo-7", uid: "demo-student-7", name: "Meera Nair", headline: "ML learner with a research mindset", skills: skills(["python", "machine learning", "sql", "data analysis", "git"]), interests: ["ai", "research", "analytics"], experienceMonths: 6, preferredMode: "Hybrid", preferredLocations: ["bengaluru", "hyderabad"], bio: "Interested in practical ML systems, experimentation and model evaluation.", year: 4, college: "RV College of Engineering", degree: "B.Tech", branch: "Computer Science", graduationYear: 2027, roles: roles(["ml engineer", "data scientist"]), candidateOptIn: true, marketOptIn: true, projects: [{ title: "Demand Forecasting", description: "Forecasted weekly demand using Python and regression models", technologies: skills(["python", "machine learning", "sql"]) }], experience: [{ title: "ML Research Assistant", description: "Compared baseline models and evaluated experiments", months: 6 }], skillDetails: [{ name: "machine learning", level: "comfortable", learnedFrom: "research" }, { name: "python", level: "advanced", learnedFrom: "projects" }], onboardingComplete: true, createdAt: ago(36), updatedAt: ago(3)
    },
    {
      id: "stu-demo-8", uid: "demo-student-8", name: "Kabir Singh", headline: "Backend and API developer", skills: skills(["javascript", "node.js", "api", "mongodb", "git"]), interests: ["cloud", "backend", "startups"], experienceMonths: 12, preferredMode: "On-site", preferredLocations: ["bengaluru"], bio: "Likes building reliable APIs and learning how products scale.", year: 3, college: "Christ University", degree: "B.Tech", branch: "Computer Science Engineering", graduationYear: 2027, roles: roles(["backend", "software engineer"]), candidateOptIn: true, marketOptIn: true, projects: [{ title: "Event API", description: "REST API for campus events with MongoDB persistence", technologies: skills(["node.js", "mongodb", "api"]) }], experience: [{ title: "Backend Intern", description: "Implemented Node.js endpoints and validation", months: 12 }], skillDetails: [{ name: "node.js", level: "advanced", learnedFrom: "internship" }, { name: "mongodb", level: "comfortable", learnedFrom: "projects" }], onboardingComplete: true, createdAt: ago(34), updatedAt: ago(1)
    },
    {
      id: "stu-demo-9", uid: "demo-student-9", name: "Ananya Iyer", headline: "Cloud and DevOps learner", skills: skills(["node.js", "cloud", "devops", "git", "api"]), interests: ["cloud", "devops", "startups"], experienceMonths: 9, preferredMode: "Flexible", preferredLocations: ["remote", "bengaluru"], bio: "Exploring cloud deployment, automation and developer tooling.", year: 4, college: "BMSCE", degree: "B.Tech", branch: "Information Science", graduationYear: 2027, roles: roles(["cloud/devops", "backend"]), candidateOptIn: true, marketOptIn: true, projects: [{ title: "DeployKit", description: "Deployment helper for Node.js applications", technologies: skills(["node.js", "cloud", "devops"]) }], experience: [{ title: "Platform Intern", description: "Improved deployment documentation and CI scripts", months: 9 }], skillDetails: [{ name: "cloud", level: "learning", learnedFrom: "projects" }, { name: "devops", level: "comfortable", learnedFrom: "internship" }], onboardingComplete: true, createdAt: ago(30), updatedAt: ago(2)
    },
    {
      id: "stu-demo-10", uid: "demo-student-10", name: "Aditya Menon", headline: "Full-stack student who likes shipping fast", skills: skills(["javascript", "react", "node.js", "sql", "git", "api"]), interests: ["product", "startups", "ai"], experienceMonths: 14, preferredMode: "Hybrid", preferredLocations: ["bengaluru", "chennai"], bio: "Full-stack builder who enjoys taking ideas from mockup to working product.", year: 4, college: "VIT Vellore", degree: "B.Tech", branch: "Computer Science", graduationYear: 2027, roles: roles(["fullstack", "software engineer"]), candidateOptIn: true, marketOptIn: true, projects: [{ title: "StudyFlow", description: "Full-stack productivity tool for students", technologies: skills(["react", "node.js", "sql"]) }], experience: [{ title: "Software Intern", description: "Shipped product features across frontend and backend", months: 14 }], skillDetails: [{ name: "react", level: "advanced", learnedFrom: "internship" }, { name: "api", level: "comfortable", learnedFrom: "projects" }], onboardingComplete: true, createdAt: ago(28), updatedAt: ago(1)
    },
    {
      id: "stu-demo-11", uid: "demo-student-11", name: "Saanvi Desai", headline: "Product-minded designer and researcher", skills: skills(["ui/ux", "product", "excel", "data analysis", "communication"]), interests: ["design", "product", "business"], experienceMonths: 5, preferredMode: "Hybrid", preferredLocations: ["bengaluru"], bio: "Combines user research with lightweight analytics to improve product decisions.", year: 2, college: "Christ University", degree: "B.Tech", branch: "Computer Science", graduationYear: 2028, roles: roles(["ui/ux designer", "product intern"]), candidateOptIn: true, marketOptIn: true, projects: [{ title: "Campus Connect", description: "User research and prototype for a student community product", technologies: skills(["ui/ux", "product"]) }], experience: [{ title: "Product Volunteer", description: "Interviewed users and mapped product requirements", months: 5 }], skillDetails: [{ name: "ui/ux", level: "advanced", learnedFrom: "projects" }, { name: "product", level: "comfortable", learnedFrom: "college" }], onboardingComplete: true, createdAt: ago(25), updatedAt: ago(4)
    },
    {
      id: "stu-demo-12", uid: "demo-student-12", name: "Vikram Shah", headline: "SQL-heavy analyst with business interest", skills: skills(["sql", "python", "excel", "data analysis", "communication"]), interests: ["analytics", "business"], experienceMonths: 3, preferredMode: "Remote", preferredLocations: ["remote", "mumbai"], bio: "Learning analytics and reporting with a focus on business questions.", year: 2, college: "NMIMS", degree: "B.Tech", branch: "Computer Engineering", graduationYear: 2028, roles: roles(["data analyst"]), candidateOptIn: true, marketOptIn: true, projects: [{ title: "Finance Dashboard", description: "SQL-backed dashboard mockup for monthly finance reporting", technologies: skills(["sql", "excel"]) }], experience: [{ title: "Analytics Trainee", description: "Prepared recurring reports and data checks", months: 3 }], skillDetails: [{ name: "sql", level: "comfortable", learnedFrom: "college" }, { name: "excel", level: "advanced", learnedFrom: "projects" }], onboardingComplete: true, createdAt: ago(23), updatedAt: ago(5)
    },
    {
      id: "stu-demo-13", uid: "demo-student-13", name: "Nidhi Kapoor", headline: "Python developer exploring AI", skills: skills(["python", "machine learning", "sql", "git"]), interests: ["ai", "research", "startups"], experienceMonths: 4, preferredMode: "Remote", preferredLocations: ["remote", "hyderabad"], bio: "Building small ML projects and learning production engineering basics.", year: 3, college: "Manipal Institute of Technology", degree: "B.Tech", branch: "CSE", graduationYear: 2027, roles: roles(["ml engineer", "software engineer"]), candidateOptIn: true, marketOptIn: true, projects: [{ title: "Resume Classifier", description: "NLP prototype that groups resumes by target role", technologies: skills(["python", "machine learning"]) }], experience: [{ title: "Research Intern", description: "Cleaned datasets and evaluated simple models", months: 4 }], skillDetails: [{ name: "python", level: "advanced", learnedFrom: "projects" }, { name: "machine learning", level: "learning", learnedFrom: "research" }], onboardingComplete: true, createdAt: ago(20), updatedAt: ago(3)
    },
    {
      id: "stu-demo-14", uid: "demo-student-14", name: "Arjun Shetty", headline: "JavaScript developer and API tinkerer", skills: skills(["javascript", "node.js", "api", "git", "cloud"]), interests: ["backend", "cloud"], experienceMonths: 8, preferredMode: "On-site", preferredLocations: ["bengaluru"], bio: "Enjoys APIs, developer tools and shipping small utilities.", year: 2, college: "Dayananda Sagar University", degree: "B.Tech", branch: "CSE", graduationYear: 2028, roles: roles(["backend", "cloud/devops"]), candidateOptIn: true, marketOptIn: true, projects: [{ title: "API Monitor", description: "Node.js utility to monitor API availability", technologies: skills(["node.js", "api", "cloud"]) }], experience: [{ title: "Developer Intern", description: "Built internal scripts and API integrations", months: 8 }], skillDetails: [{ name: "node.js", level: "comfortable", learnedFrom: "projects" }, { name: "cloud", level: "learning", learnedFrom: "college" }], onboardingComplete: true, createdAt: ago(17), updatedAt: ago(2)
    },
    {
      id: "stu-demo-15", uid: "demo-student-15", name: "Priya Joseph", headline: "UI/UX learner who prototypes in React", skills: skills(["ui/ux", "react", "javascript", "product", "communication"]), interests: ["design", "product", "startups"], experienceMonths: 2, preferredMode: "Hybrid", preferredLocations: ["bengaluru", "kochi"], bio: "Explores the space between visual design and implementation.", year: 2, college: "Christ University", degree: "B.Tech", branch: "CSE", graduationYear: 2028, roles: roles(["ui/ux designer", "frontend"]), candidateOptIn: true, marketOptIn: true, projects: [{ title: "EventPass", description: "Designed and prototyped an event booking experience", technologies: skills(["ui/ux", "react"]) }], experience: [{ title: "Design Volunteer", description: "Created screens for a student event portal", months: 2 }], skillDetails: [{ name: "ui/ux", level: "comfortable", learnedFrom: "projects" }, { name: "react", level: "learning", learnedFrom: "college" }], onboardingComplete: true, createdAt: ago(14), updatedAt: ago(4)
    },
    {
      id: "stu-demo-16", uid: "demo-student-16", name: "Dev Malhotra", headline: "Early-career full-stack learner", skills: skills(["javascript", "react", "node.js", "git"]), interests: ["startups", "product"], experienceMonths: 1, preferredMode: "Flexible", preferredLocations: ["bengaluru", "remote"], bio: "Learning full-stack development through small practical builds.", year: 1, college: "PES University", degree: "B.Tech", branch: "Computer Science", graduationYear: 2029, roles: roles(["frontend", "backend"]), candidateOptIn: true, marketOptIn: true, projects: [{ title: "Mini Portfolio", description: "Personal portfolio with React and simple API calls", technologies: skills(["react", "javascript"]) }], experience: [], skillDetails: [{ name: "javascript", level: "learning", learnedFrom: "college" }], onboardingComplete: true, createdAt: ago(10), updatedAt: ago(6)
    }
  ],

  opportunities: [
    { id: "opp-5", company: "BrightByte", companyKey: "brightbyte", title: "Software Engineering Intern", description: "Work with engineers to build APIs, fix bugs and ship production-ready features.", skills: skills(["javascript", "node.js", "api", "git"]), interests: ["startups", "product"], minExperienceMonths: 4, mode: "Hybrid", location: "Bengaluru", stipend: "₹25,000 / month", stipendAmount: 25000, stipendCurrency: "INR", roles: roles(["software engineer", "backend"]), targetYears: [2, 3, 4], organizationUid: "demo-org", createdAt: ago(2) },
    { id: "opp-6", company: "FinSight", companyKey: "finsight", title: "Business Data Intern", description: "Analyze business datasets, build recurring reports and communicate insights to stakeholders.", skills: skills(["python", "sql", "excel", "data analysis", "communication"]), interests: ["analytics", "business"], minExperienceMonths: 2, mode: "Remote", location: "India", stipend: "₹17,000 / month", stipendAmount: 17000, stipendCurrency: "INR", roles: roles(["data analyst"]), targetYears: [2, 3], organizationUid: "demo-org", createdAt: ago(3) },
    { id: "opp-7", company: "Aether AI", companyKey: "aether ai", title: "Machine Learning Intern", description: "Experiment with Python models, evaluate results and prepare datasets for AI product teams.", skills: skills(["python", "machine learning", "sql", "data analysis", "git"]), interests: ["ai", "research"], minExperienceMonths: 4, mode: "Hybrid", location: "Hyderabad", stipend: "₹28,000 / month", stipendAmount: 28000, stipendCurrency: "INR", roles: roles(["ml engineer"]), targetYears: [3, 4], organizationUid: "demo-org", createdAt: ago(4) },
    { id: "opp-8", company: "DesignDeck", companyKey: "designdeck", title: "Product Design Intern", description: "Support user research, wireframing and product discovery for a growing SaaS product.", skills: skills(["ui/ux", "product", "communication", "data analysis"]), interests: ["design", "product"], minExperienceMonths: 2, mode: "On-site", location: "Bengaluru", stipend: "₹16,000 / month", stipendAmount: 16000, stipendCurrency: "INR", roles: roles(["ui/ux designer", "product intern"]), targetYears: [2, 3], organizationUid: "demo-org", createdAt: ago(5) },
    { id: "opp-9", company: "SkyGrid", companyKey: "skygrid", title: "Cloud & DevOps Intern", description: "Learn deployment automation, cloud fundamentals and observability with platform engineers.", skills: skills(["cloud", "devops", "git", "api", "node.js"]), interests: ["cloud", "devops"], minExperienceMonths: 5, mode: "Remote", location: "India", stipend: "₹24,000 / month", stipendAmount: 24000, stipendCurrency: "INR", roles: roles(["cloud/devops"]), targetYears: [3, 4], organizationUid: "demo-org", createdAt: ago(6) },
    { id: "opp-10", company: "LoopWorks", companyKey: "loopworks", title: "Full-stack Product Intern", description: "Build React and Node.js features while partnering with product and design.", skills: skills(["react", "node.js", "javascript", "api", "git", "product"]), interests: ["product", "startups"], minExperienceMonths: 6, mode: "Hybrid", location: "Bengaluru", stipend: "₹26,000 / month", stipendAmount: 26000, stipendCurrency: "INR", roles: roles(["fullstack", "software engineer"]), targetYears: [3, 4], organizationUid: "demo-org", createdAt: ago(7) },
    { id: "opp-11", company: "HealthLens", companyKey: "healthlens", title: "Data Science Intern", description: "Explore healthcare datasets and build analytical prototypes with a data science team.", skills: skills(["python", "sql", "machine learning", "data analysis"]), interests: ["ai", "analytics"], minExperienceMonths: 5, mode: "Flexible", location: "Bengaluru", stipend: "₹23,000 / month", stipendAmount: 23000, stipendCurrency: "INR", roles: roles(["data scientist"]), targetYears: [3, 4], organizationUid: "demo-org", createdAt: ago(8) },
    { id: "opp-12", company: "OrbitPay", companyKey: "orbitpay", title: "Frontend Product Intern", description: "Create responsive React interfaces and collaborate with product managers on experiments.", skills: skills(["react", "javascript", "ui/ux", "git", "product"]), interests: ["product", "design"], minExperienceMonths: 3, mode: "On-site", location: "Bengaluru", stipend: "₹21,000 / month", stipendAmount: 21000, stipendCurrency: "INR", roles: roles(["frontend"]), targetYears: [2, 3], organizationUid: "demo-org", createdAt: ago(9) },
    { id: "opp-13", company: "CodeCove", companyKey: "codecove", title: "Backend API Intern", description: "Develop Node.js services, write validations and improve API documentation.", skills: skills(["node.js", "javascript", "api", "mongodb", "git"]), interests: ["backend", "cloud"], minExperienceMonths: 3, mode: "Remote", location: "India", stipend: "₹19,000 / month", stipendAmount: 19000, stipendCurrency: "INR", roles: roles(["backend"]), targetYears: [2, 3, 4], organizationUid: "demo-org", createdAt: ago(10) },
    { id: "opp-14", company: "MetricFlow", companyKey: "metricflow", title: "Analytics Engineering Intern", description: "Turn raw business data into reliable SQL models and dashboards for teams.", skills: skills(["sql", "python", "data analysis", "excel", "git"]), interests: ["analytics", "business"], minExperienceMonths: 3, mode: "Hybrid", location: "Bengaluru", stipend: "₹20,000 / month", stipendAmount: 20000, stipendCurrency: "INR", roles: roles(["data analyst"]), targetYears: [2, 3, 4], organizationUid: "demo-org", createdAt: ago(11) },
    { id: "opp-15", company: "NovaStack", companyKey: "novastack", title: "Junior Platform Intern", description: "Assist with cloud tooling, internal APIs and deployment workflows.", skills: skills(["cloud", "devops", "node.js", "api", "git"]), interests: ["cloud", "devops"], minExperienceMonths: 2, mode: "Flexible", location: "Remote", stipend: "₹18,000 / month", stipendAmount: 18000, stipendCurrency: "INR", roles: roles(["cloud/devops", "backend"]), targetYears: [2, 3], organizationUid: "demo-org", createdAt: ago(12) },
    { id: "opp-16", company: "PixelPilot", companyKey: "pixelpilot", title: "UI Engineering Intern", description: "Prototype accessible interfaces and translate product ideas into polished frontend experiences.", skills: skills(["react", "javascript", "ui/ux", "git"]), interests: ["design", "product"], minExperienceMonths: 2, mode: "Hybrid", location: "Bengaluru", stipend: "₹18,500 / month", stipendAmount: 18500, stipendCurrency: "INR", roles: roles(["frontend", "ui/ux designer"]), targetYears: [1, 2, 3], organizationUid: "demo-org", createdAt: ago(13) }
  ],

  applications: [
    { id: "app-demo-1", uid: "demo-student", opportunityId: "opp-1", company: "Nova Labs", title: "AI Product Intern", status: "Applied", note: "Submitted portfolio and project links.", createdAt: ago(7), updatedAt: ago(6) },
    { id: "app-demo-2", uid: "demo-student", opportunityId: "opp-2", company: "PixelForge", title: "Frontend Engineering Intern", status: "Shortlisted", note: "Recruiter shortlist received.", createdAt: ago(10), updatedAt: ago(2) },
    { id: "app-demo-3", uid: "demo-student", opportunityId: "opp-3", company: "DataMint", title: "Data Analytics Intern", status: "Interview", note: "Technical interview scheduled for Friday.", createdAt: ago(12), updatedAt: ago(1) },
    { id: "app-demo-4", uid: "demo-student", opportunityId: "opp-4", company: "CloudNest", title: "Backend & Cloud Intern", status: "Offer", note: "Offer received — comparing role scope.", createdAt: ago(15), updatedAt: ago(1) },
    { id: "app-demo-5", uid: "demo-student", opportunityId: "opp-5", company: "BrightByte", title: "Software Engineering Intern", status: "Saved", note: "Strong API + backend match.", createdAt: ago(2), updatedAt: ago(2) },
    { id: "app-demo-6", uid: "demo-student", opportunityId: "opp-8", company: "DesignDeck", title: "Product Design Intern", status: "Rejected", note: "Keep building product design evidence.", createdAt: ago(18), updatedAt: ago(8) },
    { id: "app-demo-7", uid: "demo-student", opportunityId: "opp-9", company: "SkyGrid", title: "Cloud & DevOps Intern", status: "Withdrawn", note: "Withdrew after schedule conflict.", createdAt: ago(20), updatedAt: ago(10) }
  ],

  follows: [
    { id: "follow-demo-1", uid: "demo-student", company: "Nova Labs", companyKey: "nova labs", createdAt: ago(1) },
    { id: "follow-demo-2", uid: "demo-student", company: "PixelForge", companyKey: "pixelforge", createdAt: ago(2) },
    { id: "follow-demo-3", uid: "demo-student", company: "BrightByte", companyKey: "brightbyte", createdAt: ago(3) },
    { id: "follow-demo-4", uid: "demo-student", company: "LoopWorks", companyKey: "loopworks", createdAt: ago(5) },
    { id: "follow-demo-5", uid: "demo-student", company: "OrbitPay", companyKey: "orbitpay", createdAt: ago(6) }
  ],

  activity: [
    { id: "act-demo-1", uid: "demo-student", type: "view", opportunityId: "opp-2", company: "PixelForge", title: "Frontend Engineering Intern", createdAt: ago(1) },
    { id: "act-demo-2", uid: "demo-student", type: "save", opportunityId: "opp-5", company: "BrightByte", title: "Software Engineering Intern", createdAt: ago(2) },
    { id: "act-demo-3", uid: "demo-student", type: "view", opportunityId: "opp-10", company: "LoopWorks", title: "Full-stack Product Intern", createdAt: ago(3) },
    { id: "act-demo-4", uid: "demo-student", type: "view", opportunityId: "opp-12", company: "OrbitPay", title: "Frontend Product Intern", createdAt: ago(4) },
    { id: "act-demo-5", uid: "demo-student", type: "apply", opportunityId: "opp-1", company: "Nova Labs", title: "AI Product Intern", createdAt: ago(7) },
    { id: "act-demo-6", uid: "demo-student", type: "apply", opportunityId: "opp-3", company: "DataMint", title: "Data Analytics Intern", createdAt: ago(12) },
    { id: "act-demo-7", uid: "demo-student", type: "view", opportunityId: "opp-13", company: "CodeCove", title: "Backend API Intern", createdAt: ago(2) },
    { id: "act-demo-8", uid: "demo-student", type: "view", opportunityId: "opp-16", company: "PixelPilot", title: "UI Engineering Intern", createdAt: ago(6) }
  ]
};
