import "dotenv/config";
import http from "node:http";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { connectMongo, getDb } from "./mongodb.js";
import { ensureStudentForUser, getStudent, listStudents, updateStudent, createStudent, listOpportunities, getOpportunity, createOpportunity, seedDatabase } from "./db.js";
import { rankMatches } from "./matcher.js";
import { parseStudentText, parseJobText, skillpulse, careerGap, interviewQuestions } from "./ai.js";

const root=path.join(path.dirname(fileURLToPath(import.meta.url)),"..","client");
const port=Number(process.env.PORT||4000); const frontendUrl=process.env.FRONTEND_URL||`http://localhost:${port}`; const localAuth=process.env.LOCAL_AUTH!=="false";
const cors=res=>{res.setHeader("Access-Control-Allow-Origin",frontendUrl==="*"?"*":frontendUrl);res.setHeader("Access-Control-Allow-Headers","Content-Type, Authorization, X-Local-User, X-Local-Role");res.setHeader("Access-Control-Allow-Methods","GET,POST,PUT,DELETE,OPTIONS");};
const json=(res,s,d)=>{cors(res);res.writeHead(s,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(d));};
const readBody=req=>new Promise((resolve,reject)=>{let s="";req.on("data",c=>{s+=c;if(s.length>1e6)reject(new Error("Request too large"));});req.on("end",()=>{try{resolve(s?JSON.parse(s):{});}catch{reject(new Error("Invalid JSON"));}});});
const cleanList=x=>Array.isArray(x)?[...new Set(x.map(v=>String(v).trim().toLowerCase()).filter(Boolean))]:String(x||"").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean);
const noId=x=>{if(!x)return x;const{_id,...r}=x;return r;};
async function auth(req,res){if(localAuth)return{uid:req.headers["x-local-user"]||"demo-student",role:req.headers["x-local-role"]||"student",email:`${req.headers["x-local-user"]||"demo-student"}@local.test`};const{firebaseAuth}=await import("./firebase-admin.js");const h=req.headers.authorization||"";if(!h.startsWith("Bearer ")){json(res,401,{error:"Authentication required"});return null;}try{const t=await firebaseAuth.verifyIdToken(h.slice(7));return{...t,role:t.role||"student"};}catch{json(res,401,{error:"Invalid or expired authentication token"});return null;}}
async function col(n){return getDb().collection(n);} async function all(n,q={}){return(await(await col(n)).find(q).toArray()).map(noId);}
async function profile(user){const s=await listStudents(user.uid);return s[0]||ensureStudentForUser(user.uid,user.email);}
async function market(){const ss=await all("students"),os=await listOpportunities(),sm=new Map(),rm=new Map(),dm=new Map();for(const s of ss){for(const x of s.skills||[])sm.set(x,(sm.get(x)||0)+1);for(const r of (s.roles||[]).filter(Boolean))rm.set(r,(rm.get(r)||0)+1);}for(const o of os)for(const x of o.skills||[])dm.set(x,(dm.get(x)||0)+1);return{students:ss.length,opportunities:os.length,skills:[...sm].map(([skill,students])=>({skill,students,openings:dm.get(skill)||0})).sort((a,b)=>b.students-a.students),roles:[...rm].map(([role,students])=>({role,students})).sort((a,b)=>b.students-a.students)};}
function companyFeed(jobs){const by=new Map();for(const o of jobs){if(!by.has(o.company))by.set(o.company,[]);by.get(o.company).push(o);}return[...by].map(([company,items])=>({company,headline:`${company} is hiring`,summary:`${items.length} visible opportunity${items.length>1?"ies":"y"} with active student-facing roles.`,roles:items.map(o=>({id:o.id,title:o.title,mode:o.mode,location:o.location,stipend:o.stipend,skills:o.skills,industry:o.industry||"Technology"})),updatedAt:new Date().toISOString()}));}
async function personalized(user){const p=await profile(user),jobs=await listOpportunities(),f=await all("follows",{uid:user.uid}),a=await all("applications",{uid:user.uid}),followed=new Set(f.map(x=>x.company));const scored=rankMatches(p,jobs).map(m=>{let bonus=followed.has(m.opportunity.company)?12:0;const applied=a.some(x=>x.opportunityId===m.opportunity.id);return{...m,score:Math.min(100,m.score+bonus),personalizedReasons:[...(m.reasons||[]),...(followed.has(m.opportunity.company)?["You follow this company"]:[]),...(applied?["You already interacted with this role"]:[])]};}).sort((x,y)=>y.score-x.score);return{matches:scored.slice(0,10),followed:[...followed],signals:{applications:a.length,follows:f.length}};}

const server=http.createServer(async(req,res)=>{try{if(req.method==="OPTIONS"){cors(res);res.writeHead(204);return res.end();}const url=new URL(req.url,`http://${req.headers.host}`);if(url.pathname==="/api/health")return json(res,200,{ok:true,service:"skillbridge",localAuth,ai:true});if(!url.pathname.startsWith("/api/"))return serve(req,res);const user=await auth(req,res);if(!user)return;
if(url.pathname==="/api/me"&&req.method==="GET")return json(res,200,{user,profile:await profile(user)});
if(url.pathname==="/api/students"&&req.method==="GET")return json(res,200,await listStudents(user.uid));
if(url.pathname==="/api/students"&&req.method==="POST"){if(user.role!=="student")return json(res,403,{error:"Student account required"});const d=await readBody(req);if(!d.name)return json(res,400,{error:"Name is required"});return json(res,201,await createStudent({...d,skills:cleanList(d.skills),interests:cleanList(d.interests)},user.uid));}
if(url.pathname.startsWith("/api/students/")&&req.method==="GET"){const s=await getStudent(Number(url.pathname.split("/").pop()),user.uid);return s?json(res,200,s):json(res,404,{error:"Student not found"});}
if(url.pathname.startsWith("/api/students/")&&req.method==="PUT"){if(user.role!=="student")return json(res,403,{error:"Student account required"});const d=await readBody(req);const s=await updateStudent(Number(url.pathname.split("/").pop()),{...d,skills:cleanList(d.skills),interests:cleanList(d.interests)},user.uid);return s?json(res,200,s):json(res,404,{error:"Student not found"});}
if(url.pathname==="/api/opportunities"&&req.method==="GET"){let rows=await listOpportunities();const q=(url.searchParams.get("q")||"").toLowerCase(),mode=url.searchParams.get("mode"),year=url.searchParams.get("year"),skill=url.searchParams.get("skill");if(q)rows=rows.filter(o=>`${o.company} ${o.title} ${o.description} ${(o.skills||[]).join(" ")}`.toLowerCase().includes(q));if(mode)rows=rows.filter(o=>o.mode===mode);if(skill)rows=rows.filter(o=>(o.skills||[]).includes(skill));if(year)rows=rows.filter(o=>(o.targetYears||[]).map(String).includes(String(year)));return json(res,200,rows);}
if(url.pathname==="/api/opportunities"&&req.method==="POST"){if(user.role!=="organization")return json(res,403,{error:"Organization account required"});const d=await readBody(req);if(!d.company||!d.title||!d.description)return json(res,400,{error:"Company, role and description are required"});const parsed=parseJobText(`${d.title} ${d.description} ${(d.skills||[]).join(" ")}`);return json(res,201,await createOpportunity({...d,skills:[...new Set([...cleanList(d.skills),...parsed.skills])],interests:cleanList(d.interests),roles:parsed.roles,organizationUid:user.uid,industry:d.industry||"Technology",targetYears:d.targetYears||[]}));}
if(url.pathname.startsWith("/api/opportunities/")&&req.method==="GET"){const o=await getOpportunity(Number(url.pathname.split("/").pop()));return o?json(res,200,o):json(res,404,{error:"Opportunity not found"});}
if(url.pathname.startsWith("/api/matches/")&&req.method==="GET"){const s=await getStudent(Number(url.pathname.split("/").pop()),user.uid);if(!s)return json(res,404,{error:"Student not found"});return json(res,200,{student:s,matches:rankMatches(s,await listOpportunities())});}
if(url.pathname==="/api/recommendations"&&req.method==="GET"){if(user.role!=="student")return json(res,403,{error:"Student account required"});return json(res,200,await personalized(user));}
if(url.pathname==="/api/feed"&&req.method==="GET"){const jobs=await listOpportunities(),f=await all("follows",{uid:user.uid}),followed=new Set(f.map(x=>x.company)),items=companyFeed(jobs).filter(c=>followed.size?followed.has(c.company):true);return json(res,200,{following:[...followed],items});}
if(url.pathname==="/api/activity"&&req.method==="POST"){const d=await readBody(req),c=await col("activity");await c.insertOne({uid:user.uid,type:d.type||"view",opportunityId:Number(d.opportunityId)||null,company:d.company||"",createdAt:new Date().toISOString()});return json(res,201,{ok:true});}
if(url.pathname==="/api/ai/profile"&&req.method==="POST"){const d=await readBody(req);return json(res,200,parseStudentText(d.text||""));}
if(url.pathname==="/api/ai/job"&&req.method==="POST"){const d=await readBody(req);return json(res,200,parseJobText(d.text||""));}
if(url.pathname==="/api/ai/skillpulse"&&req.method==="GET"){if(user.role!=="student")return json(res,403,{error:"Student account required"});return json(res,200,skillpulse(await profile(user),await all("students"),await listOpportunities()));}
if(url.pathname==="/api/ai/career"&&req.method==="GET")return json(res,200,careerGap(await profile(user),url.searchParams.get("role")||"software engineer",await listOpportunities()));
if(url.pathname.startsWith("/api/ai/interview/")&&req.method==="GET"){const o=await getOpportunity(Number(url.pathname.split("/").pop()));if(!o)return json(res,404,{error:"Opportunity not found"});return json(res,200,{opportunity:o,questions:interviewQuestions(o,await profile(user))});}
if(url.pathname==="/api/market"&&req.method==="GET"){if(user.role!=="organization")return json(res,403,{error:"Organization account required"});return json(res,200,await market());}
if(url.pathname==="/api/applications"&&req.method==="GET")return json(res,200,await all("applications",{uid:user.uid}));
if(url.pathname==="/api/applications"&&req.method==="POST"){if(user.role!=="student")return json(res,403,{error:"Student account required"});const d=await readBody(req),o=await getOpportunity(Number(d.opportunityId));if(!o)return json(res,404,{error:"Opportunity not found"});const c=await col("applications"),e=await c.findOne({uid:user.uid,opportunityId:o.id});if(e)return json(res,200,noId(e));const a={id:`app-${Date.now()}`,uid:user.uid,opportunityId:o.id,company:o.company,title:o.title,status:"Applied",note:"",createdAt:new Date().toISOString()};await c.insertOne(a);await(await col("activity")).insertOne({uid:user.uid,type:"apply",opportunityId:o.id,company:o.company,createdAt:new Date().toISOString()});return json(res,201,a);}
if(url.pathname.startsWith("/api/applications/")&&req.method==="PUT"){const id=decodeURIComponent(url.pathname.split("/").pop()),d=await readBody(req),c=await col("applications");const found=await c.findOne({uid:user.uid,id});if(!found)return json(res,404,{error:"Application not found"});const updated=await c.findOneAndUpdate({uid:user.uid,id},{$set:{status:d.status||found.status,note:String(d.note||"") }},{returnDocument:"after"});return json(res,200,noId(updated));}
if(url.pathname==="/api/follows"&&req.method==="GET")return json(res,200,await all("follows",{uid:user.uid}));
if(url.pathname==="/api/follows"&&req.method==="POST"){const d=await readBody(req),c=await col("follows"),key={uid:user.uid,company:String(d.company)};const e=await c.findOne(key);if(e){await c.deleteOne(key);return json(res,200,{following:false});}await c.insertOne({...key,createdAt:new Date().toISOString()});return json(res,201,{following:true});}
if(url.pathname==="/api/company-intel"&&req.method==="GET"){const q=(url.searchParams.get("q")||"").toLowerCase(),jobs=await listOpportunities(),similar=jobs.filter(o=>`${o.company} ${o.title} ${(o.skills||[]).join(" ")}`.toLowerCase().includes(q));return json(res,200,{query:q,companies:[...new Set(similar.map(o=>o.company))],offerings:similar.map(o=>({company:o.company,role:o.title,mode:o.mode,stipend:o.stipend,skills:o.skills}))});}
return json(res,404,{error:"API route not found"});
}catch(error){console.error(error);return json(res,500,{error:"Unexpected server error",detail:error.message});}});
function serve(req,res){let p=new URL(req.url,`http://${req.headers.host}`).pathname;if(p==="/")p="/index.html";const file=path.join(root,path.normalize(p).replace(/^[/\\]+/,""));if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return json(res,404,{error:"Not found"});const types={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8"};cors(res);res.writeHead(200,{"Content-Type":types[path.extname(file)]||"application/octet-stream"});fs.createReadStream(file).pipe(res);}
await connectMongo();await seedDatabase();server.listen(port,()=>console.log(`SkillBridge running locally at http://localhost:${port}`));
