import { semanticSimilarity } from "./ai.js";

const RELATED={javascript:["react","node.js","typescript","express"],react:["javascript","next.js","frontend","ui/ux"],"node.js":["javascript","express","backend","api"],python:["data analysis","machine learning","pandas","flask"],"machine learning":["python","ai","data analysis","tensorflow","pytorch"],sql:["database","mysql","postgresql","sqlite"],figma:["ui/ux","product design","wireframing"],"ui/ux":["figma","product design","wireframing"],"data analysis":["python","sql","pandas","excel"],cloud:["aws","azure","gcp","devops"],aws:["cloud","devops"],git:["github","version control","open source"],communication:["presentation","teamwork","collaboration"],product:["product management","research","analytics"]};
const ROLE_ALIASES={frontend:["frontend","front end","react developer","ui developer"],backend:["backend","back end","node developer","api developer"],fullstack:["full stack","fullstack","full-stack"],"data analyst":["data analyst","analytics","business analyst"],"data scientist":["data scientist","data science"],"ml engineer":["ml engineer","machine learning engineer","ai engineer"],"software engineer":["software engineer","software developer","sde"],"ui/ux designer":["ui/ux","ux designer","product designer"],"cloud/devops":["cloud","devops","site reliability"]};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const cleanList=v=>[...new Set((v||[]).map(x=>String(x).trim().toLowerCase()).filter(Boolean))];
function jaccard(a,b){const A=new Set(cleanList(a)),B=new Set(cleanList(b));if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/new Set([...A,...B]).size;}
function roleFit(studentRoles,opportunityRoles){const a=cleanList(studentRoles),b=cleanList(opportunityRoles);if(!a.length||!b.length)return 0;let hits=0;for(const role of a){if(b.includes(role)||((ROLE_ALIASES[role]||[]).some(x=>b.includes(x))))hits++;}return clamp(hits/Math.min(a.length,b.length));}
function relatedOverlap(studentSkills,requiredSkills){const s=cleanList(studentSkills),r=cleanList(requiredSkills);if(!r.length)return 0;let hits=0;for(const req of r)if(!s.includes(req)&&(RELATED[req]||[]).some(x=>s.includes(x)))hits++;return hits/r.length;}
function experienceFit(studentMonths=0,requiredMonths=0){if(!requiredMonths)return 1;return clamp(Number(studentMonths||0)/Number(requiredMonths||1));}
function workModeFit(studentMode,opportunityMode){if(!studentMode||!opportunityMode||opportunityMode.toLowerCase()==="flexible")return 1;return studentMode.toLowerCase()===opportunityMode.toLowerCase()?1:0.25;}
function educationFit(student,o){if(!o.targetYears?.length)return 1;return o.targetYears.map(Number).includes(Number(student.year))?1:0;}
function locationFit(student,o){const prefs=cleanList(student.preferredLocations);if(!prefs.length||!o.location)return .5;const loc=String(o.location).toLowerCase();if(prefs.some(x=>loc.includes(x)||x.includes(loc)))return 1;if(prefs.includes("remote")&&String(o.mode).toLowerCase()==="remote")return 1;return .15;}
function skillConfidence(student,required){const details=new Map((student.skillDetails||[]).map(x=>[String(x.name||"").toLowerCase(),String(x.level||"").toLowerCase()]));const levels={beginner:.45,learning:.65,comfortable:.82,advanced:.94,expert:1};if(!required.length)return 0;let total=0;for(const s of required){if(!(student.skills||[]).map(String).map(x=>x.toLowerCase()).includes(s))continue;total+=levels[details.get(s)]||.7;}return total/required.length;}
function evidenceFit(student,required){const projects=(student.projects||[]).map(p=>`${p.title||""} ${p.description||""} ${(p.technologies||[]).join(" ")}`.toLowerCase()).join(" ");const experience=(student.experience||[]).map(p=>`${p.title||""} ${p.description||""}`.toLowerCase()).join(" ");if(!required.length)return 0;let hit=0;for(const skill of required){const s=String(skill).toLowerCase();if(projects.includes(s))hit+=.65;if(experience.includes(s))hit+=.35;}return clamp(hit/required.length);}
function personalizationSignals(student,opportunity,activity=[],follows=[]){const company=String(opportunity.company||"").toLowerCase();const relevant=activity.filter(a=>String(a.company||"").toLowerCase()===company);const followed=follows.some(f=>String(f.company||"").toLowerCase()===company);const sameRoles=jaccard(student.roles,opportunity.roles);const repeated=clamp(relevant.length/3);return{followed,activityBoost:clamp(repeated*.7+(followed?.3:0)),roleHistory:sameRoles};}
function textScore(student,opportunity){const source=[...(student.skills||[]),...(student.interests||[]),...(student.roles||[]),student.headline,student.bio,...(student.preferredLocations||[])].filter(Boolean).join(" ");const target=[opportunity.title,opportunity.description,...(opportunity.skills||[]),...(opportunity.interests||[]),...(opportunity.roles||[]),opportunity.location].filter(Boolean).join(" ");return semanticSimilarity(source,target);}
function matchStudentToOpportunity(student,opportunity,context={}){
 const skills=cleanList(student.skills),required=cleanList(opportunity.skills);const exact=required.length?skills.filter(x=>required.includes(x)).length/required.length:0;const related=relatedOverlap(skills,required);const confidence=skillConfidence(student,required);const evidence=evidenceFit(student,required);const interest=jaccard(student.interests,opportunity.interests);const experience=experienceFit(student.experienceMonths,opportunity.minExperienceMonths);const mode=workModeFit(student.preferredMode,opportunity.mode);const education=educationFit(student,opportunity);const location=locationFit(student,opportunity);const roles=roleFit(student.roles,opportunity.roles);const text=textScore(student,opportunity);const personalization=personalizationSignals(student,opportunity,context.activity||[],context.follows||[]);
 const eligible=education===1&&experience>=1;
 const base=.24*exact+.12*related+.10*confidence+.10*evidence+.10*roles+.08*interest+.08*experience+.05*mode+.05*education+.04*location+.04*text;
 const personalized=clamp(base*.92+personalization.activityBoost*.05+personalization.roleHistory*.03);
 const score=Math.round(personalized*100);
 const exactMatches=required.filter(x=>skills.includes(x));const relatedMatches=required.filter(x=>!skills.includes(x)&&(RELATED[x]||[]).some(a=>skills.includes(a)));const gaps=required.filter(x=>!skills.includes(x));
 const reasons=[];if(exactMatches.length)reasons.push(`${exactMatches.length}/${required.length} required skills matched`);if(confidence>.75)reasons.push("Strong skill confidence");if(evidence>.35)reasons.push("Project/experience evidence found");if(roles>=.5)reasons.push("Target role aligned");if(location>=.8)reasons.push("Location preference aligned");if(personalization.followed)reasons.push("You follow this company");if(personalization.activityBoost>.2)reasons.push("Similar activity with this company");if(!reasons.length)reasons.push("Partial profile-to-role similarity");
 return {eligible,score,components:{exactSkill:Math.round(exact*100),relatedSkill:Math.round(related*100),skillConfidence:Math.round(confidence*100),evidence:Math.round(evidence*100),roleFit:Math.round(roles*100),interest:Math.round(interest*100),experience:Math.round(experience*100),workMode:Math.round(mode*100),education:Math.round(education*100),location:Math.round(location*100),semantic:Math.round(text*100),personalization:Math.round(personalization.activityBoost*100)},reasons,gaps,personalization,explainability:{formula:"0.24E + 0.12R + 0.10C + 0.10V + 0.10Role + 0.08I + 0.08X + 0.05M + 0.05Edu + 0.04Loc + 0.04Sem; personalized adjustment capped at 8 percentage points",weights:{exactSkill:24,relatedSkill:12,skillConfidence:10,evidence:10,roleFit:10,interest:8,experience:8,workMode:5,education:5,location:4,semantic:4}}};
}
function rankMatches(student,opportunities,context={}){return opportunities.map(opportunity=>({opportunity,...matchStudentToOpportunity(student,opportunity,context)})).sort((a,b)=>Number(b.eligible)-Number(a.eligible)||b.score-a.score);}
export{cleanList,jaccard,relatedOverlap,matchStudentToOpportunity,rankMatches};