import { semanticSimilarity } from "./ai.js";
const RELATED={javascript:["react","node.js","typescript","express"],react:["javascript","next.js","frontend","ui/ux"],"node.js":["javascript","express","backend","api"],python:["data analysis","machine learning","pandas","flask"],"machine learning":["python","ai","data analysis","tensorflow","pytorch"],sql:["database","mysql","postgresql","sqlite"],figma:["ui/ux","product design","wireframing"],"ui/ux":["figma","product design","wireframing"],"data analysis":["python","sql","pandas","excel"],cloud:["aws","azure","gcp","devops"],aws:["cloud","devops"],git:["github","version control","open source"],communication:["presentation","teamwork","collaboration"],product:["product management","research","analytics"]};
const ROLE_ALIASES={frontend:["frontend","front end","react developer","ui developer"],backend:["backend","back end","node developer","api developer"],fullstack:["full stack","fullstack","full-stack"],"data analyst":["data analyst","analytics","business analyst"],"data scientist":["data scientist","data science"],"ml engineer":["ml engineer","machine learning engineer","ai engineer"],"software engineer":["software engineer","software developer","sde"],"ui/ux designer":["ui/ux","ux designer","product designer"],"cloud/devops":["cloud","devops","site reliability"]};
const LEVEL={beginner:.45,learning:.65,comfortable:.82,advanced:1,expert:1};
const clean=v=>[...new Set((v||[]).map(x=>String(x).trim().toLowerCase()).filter(Boolean))];
const jaccard=(a,b)=>{const A=new Set(clean(a)),B=new Set(clean(b));if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/new Set([...A,...B]).size};
const roleFit=(a,b)=>{a=clean(a);b=clean(b);if(!b.length)return 0;let hits=0;for(const r of a)if(b.includes(r)||(ROLE_ALIASES[r]||[]).some(x=>b.includes(x)))hits++;return Math.min(1,hits/Math.max(1,b.length));};
const related=(a,b)=>{a=clean(a);b=clean(b);if(!b.length)return 0;return b.filter(r=>!a.includes(r)&&(RELATED[r]||[]).some(x=>a.includes(x))).length/b.length};
const experience=(m,r)=>!r?1:Math.min(1,Number(m||0)/Number(r));
const mode=(a,b)=>!a||!b||b.toLowerCase()==="flexible"?1:a.toLowerCase()===b.toLowerCase()?1:.2;
const education=(s,o)=>!o.targetYears?.length||o.targetYears.map(Number).includes(Number(s.year))?1:.35;
function confidence(student,required){const details=new Map((student.skillDetails||[]).map(x=>[String(x.name).toLowerCase(),LEVEL[String(x.level||"").toLowerCase()]||.65]));if(!required.length)return 0;let total=0;for(const x of required){const name=String(x).toLowerCase();total+=details.get(name)||((student.skills||[]).map(String).map(x=>x.toLowerCase()).includes(name)?.55:0)}return total/required.length;}
function evidence(student,required){const ps=(student.projects||[]).map(p=>`${p.title||""} ${p.description||""} ${(p.technologies||[]).join(" ")}`).join(" ").toLowerCase();const ex=(student.experience||[]).map(p=>`${p.title||""} ${p.description||""}`).join(" ").toLowerCase();if(!required.length)return 0;let total=0;for(const r of required){const x=String(r).toLowerCase();if(ps.includes(x))total+=.65;if(ex.includes(x))total+=.35}return Math.min(1,total/required.length);}
function locationFit(s,o){const pref=clean(s.preferredLocations),loc=String(o.location||"").toLowerCase();if(!pref.length||!loc)return .5;if(pref.some(x=>loc.includes(x)||x.includes(loc)))return 1;if(pref.includes("remote")&&String(o.mode||"").toLowerCase()==="remote")return 1;return .2;}
function text(s,o){const a=[...(s.skills||[]),...(s.interests||[]),...(s.roles||[]),s.headline,s.bio,...(s.projects||[]).flatMap(p=>[p.title,p.description,...(p.technologies||[])])].filter(Boolean).join(" ");const b=[o.title,o.description,...(o.skills||[]),...(o.interests||[]),...(o.roles||[]),o.location].filter(Boolean).join(" ");return semanticSimilarity(a,b);}
export function matchStudentToOpportunity(student,o){const skills=clean(student.skills),req=clean(o.skills),exact=req.length?req.filter(x=>skills.includes(x)).length/req.length:0,rel=related(skills,req),interest=jaccard(student.interests,o.interests),exp=experience(student.experienceMonths,o.minExperienceMonths),work=mode(student.preferredMode,o.mode),edu=education(student,o),role=roleFit(student.roles,o.roles),conf=confidence(student,req),ev=evidence(student,req),loc=locationFit(student,o),sem=text(student,o);const eligible=exp>=.5&&edu>=.35;const raw=exact*.24+rel*.10+conf*.10+ev*.10+role*.10+interest*.08+exp*.08+work*.05+edu*.05+loc*.04+sem*.06;const score=Math.round(raw*100);const gaps=req.filter(x=>!skills.includes(x));const reasons=[];if(exact)reasons.push(`${Math.round(exact*100)}% required-skill coverage`);if(conf>=.7)reasons.push("Strong skill-confidence evidence");if(ev>=.35)reasons.push("Projects or experience support the role");if(role>=.5)reasons.push("Target role aligned");if(loc===1)reasons.push("Location preference aligned");if(work===1)reasons.push("Work mode aligned");if(sem>=.35)reasons.push("Relevant profile and role context");if(!eligible)reasons.unshift("Below the current experience/education eligibility threshold");return{eligible,score,components:{exactSkill:Math.round(exact*100),relatedSkill:Math.round(rel*100),skillConfidence:Math.round(conf*100),evidence:Math.round(ev*100),roleFit:Math.round(role*100),interest:Math.round(interest*100),experience:Math.round(exp*100),workMode:Math.round(work*100),education:Math.round(edu*100),location:Math.round(loc*100),semantic:Math.round(sem*100)},gaps,reasons,explainability:{formula:"0.24E+0.10R+0.10C+0.10V+0.10Role+0.08I+0.08X+0.05M+0.05Edu+0.04L+0.06S",weights:{exactSkill:.24,relatedSkill:.10,skillConfidence:.10,evidence:.10,roleFit:.10,interest:.08,experience:.08,workMode:.05,education:.05,location:.04,semantic:.06}}};}
export function rankMatches(student,ops){return ops.map(opportunity=>({opportunity,...matchStudentToOpportunity(student,opportunity)})).sort((a,b)=>Number(b.eligible)-Number(a.eligible)||b.score-a.score);}
export { clean, jaccard, related };
